### ISSUE TITLE
建议增加一个启动成功/失败状态提示

### ISSUE THREAD

**Issue by pmkol** [morytyann/OpenWrt-mihomo#1]
目前启动后没有状态提示，希望能加一个，非常Nice的插件，感谢作者

**Comment by morytyann** [comment]
抱歉之前没有看到Issue，非常感谢PR，我在PR的基础上做了修改：
- 添加了ubus list service的权限，现在应该可以正确显示状态了。
- 将状态移动到了基础配置下。
![image](https://github.com/morytyann/OpenWrt-mihomo/assets/10665459/148688cf-c9a0-4928-a5b0-5040bb196fac)
