### ISSUE TITLE
建议增加日志记录和插件功能

### ISSUE THREAD

**Issue by luestr** [morytyann/OpenWrt-mihomo#10]
有时候插件运行异常需要查看插件本身的日志，以帮助分析问题或反馈。

**Comment by morytyann** [comment]
功能更新：
1. 添加插件日志
2. 保存内核日志
3. LuCI添加日志查看功能

已知问题：
如果在核心运行中清空核心日志会导致其无法被查看，因此只能在完全重启时清空，所以现在没有定时或按文件大小清空核心日志的功能，建议开启定时重启确保核心日志不会过大
