### ISSUE TITLE
请问Mihomo内核路径在哪里？

### ISSUE THREAD

**Issue by jklolixxs** [morytyann/OpenWrt-mihomo#108]
请问Mihomo内核路径在哪里？我需要使用Alpha版本的内核，插件上并没有看到替换内核的地方，所以我想自己手动切换内核，后续就可以通过metacubexd面板更新了

**Comment by morytyann** [comment]
内核路径：`/usr/bin/mihomo`。
另外v1.7.0已经切换到Alpha内核了，直接升级到v1.7.0也可以的。

**Comment by jklolixxs** [comment]
谢谢
