### ISSUE TITLE
启动后无规则、无节点

### ISSUE THREAD

**Issue by luestr** [morytyann/OpenWrt-mihomo#11]
1. 已确认配置文件正确无误，在 OpenClash 和 Clash Verge 上均可正常运行；
2. 不管是覆盖升级，还是卸载重装今天的最新版，依然无法看到规则和节点被成功下载下来。节点数量为0，规则数量也是0；
3. `/etc/mihomo/run/proxy_provider` 存在上次下载下来的有效的订阅文件
4. `/etc/mihomo/run/RuleSet` 存在上次下载下来的有效的规则文件
5. 尝试在WebUI上手动更新节点订阅和规则集合无效；
6. 所涉及的版本是今天的编译产出。

**Comment by morytyann** [comment]
打开面板后打开开发者工具（F12），刷新页面后看一下有没有报错的请求，有的话麻烦贴一下日志

**Comment by morytyann** [comment]
使用火狐浏览器测试，复现了插件页面的错误，将会修复；但没有复现metacubexd面板的错误。
发一下脱敏后的配置文件吧

**Comment by morytyann** [comment]
这个时候网络正常吗？

**Comment by morytyann** [comment]
我又用你提供的配置文件，只添加了proxy-provider，关闭了混入，测试依旧不能复现
![image](https://github.com/morytyann/OpenWrt-mihomo/assets/10665459/6b3beef1-23b4-4a9d-baee-5b0e53234ef8)
在面板取消启用后保存并应用，然后SSH进去运行`/usr/bin/mihomo -d /etc/mihomo/run`，运行日志贴一下，顺便打开面板看看这时是否正常

**Comment by morytyann** [comment]
应该是TUN的问题，你删掉配置文件中的TUN再试试

**Comment by morytyann** [comment]
我的测试环境下TUN是无法启动的，目前插件也不支持启用TUN，在考虑是否需要在启动前删除TUN配置

**Comment by morytyann** [comment]
修改的是`/etc/mihomo/run/config.yaml`吗？

**Comment by morytyann** [comment]
嗯嗯，因为不是通过插件启动的，并不会将上传的文件移动到运行目录下

**Comment by morytyann** [comment]
再试一下通过插件启动吧，记得使用删掉TUN的配置文件

**Comment by morytyann** [comment]
卸载后，运行如下脚本清理文件
```
rm -rf /etc/mihomo
rm -f /etc/config/mihomo
rm -f /etc/config/mihomo-opkg
```
然后重新安装一下再试试

**Comment by morytyann** [comment]
保留依赖没问题的
在LuCI界面勾选启用，保存并应用后，运行一下`service mihomo reload`看看输出吧

**Comment by morytyann** [comment]
现在的情况应该也是刚才启动TUN导致的后遗症，重启一下路由器试试呢

**Comment by morytyann** [comment]
目前只能猜测是与固件/依赖版本的兼容性问题了

**Comment by morytyann** [comment]
那我用虚拟机再测试一下
如果还不能复现的话，我会关掉这个ISSUE，标记为不能复现

**Comment by morytyann** [comment]
你是自己编译的还是直接下载的？插件只支持firewall4，我直接下载这个固件使用的是firewall3

**Comment by morytyann** [comment]
启动不了是因为发现缺少procd-ujail这个包

**Comment by morytyann** [comment]
好的
