### ISSUE TITLE
[Feature Request] 绕过中国大陆IP可以自定义源且能定时自动更新

### ISSUE THREAD

**Issue by Moexin** [morytyann/OpenWrt-mihomo#110]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

绕过中国大陆IP目前发现是写死在nft规则里的，可否实现类似于OpenClash自定义源且能定时更新呢？

### 如何实现

可以写个定时脚本从[V4V6混合单文件](https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list)中提取V4V6地址分别替换进[geoip_cn.nft](https://github.com/morytyann/OpenWrt-mihomo/blob/main/mihomo/files/nftables/geoip_cn.nft)和[geoip6_cn.nft](https://github.com/morytyann/OpenWrt-mihomo/blob/main/mihomo/files/nftables/geoip6_cn.nft)

也可以写个定时脚本从[V4单文件](https://ispip.clang.cn/all_cn.txt)中提取V4地址替换进[geoip_cn.nft](https://github.com/morytyann/OpenWrt-mihomo/blob/main/mihomo/files/nftables/geoip_cn.nft)接着从[V6单文件](https://ispip.clang.cn/all_cn_ipv6.txt)中提取V6地址替换进[geoip6_cn.nft](https://github.com/morytyann/OpenWrt-mihomo/blob/main/mihomo/files/nftables/geoip6_cn.nft)

**Comment by morytyann** [comment]
我觉得我定期更新一下文件就行了，没有必要做个定时更新的功能。至于自定义源，这些库的数据源都大差不差，也没太大意义……

**Comment by Moexin** [comment]
好的
