### ISSUE TITLE
[Feature Request]建议优化界面显示名称为OP-Mihomo或者其他

### ISSUE THREAD

**Issue by utopeadia** [morytyann/OpenWrt-mihomo#111]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

最近遇到一些小白的提问Mihomo和内核同名导致不能很好的解决问题，如果显著表示软件名称与内核名称区分开会好一些。

**Comment by morytyann** [comment]
嗯，已经决定要改名了

**Comment by morytyann** [comment]
这个先关了，等我确定好名字就更换，感谢Issue❤️
