### ISSUE TITLE
[BUG] 最新版面板内存显示问题

### ISSUE THREAD

**Issue by ForestL18** [morytyann/OpenWrt-mihomo#113]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt 23.05.3 r27917-81a1f98d5b

### 插件版本

1.7.1

### 硬件架构

aarch64_generic

### BUG 描述

使用最新的openwrt-mihomo源码和alpha-41efc5e的mihomo源码编译的插件运行后在metacubex面板查看信息，发现内存显示仅有`1.3M`，显然不正常🤣

![image](https://github.com/user-attachments/assets/5e5a9985-227b-4170-9bd5-6801113eda90)

构建时使用openwrt官方fork的[gh-action-sdk]，修改如下：

修改golang版本
```
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 23.x feeds/packages/lang/golang
sed -i 's/CPU_CFLAGS = -Os -pipe/CPU_CFLAGS = -O3 -mtune=generic -pipe/g' include/target.mk
```

去掉hash检查
```
:<<!
		badhash_msg="HASH does not match "
		badhash_msg+="|HASH uses deprecated hash,"
		badhash_msg+="|HASH is missing,"
		if grep -qE "$badhash_msg" logtmp; then
			echo "Package HASH check failed"
			exit 1
		fi
!
```

### 预期行为

正常mihomo内存应该是50M+，这是否是因为openwrt官方上游未更新go 1.23导致的？🤔

### 复现步骤

如上

### 插件配置

配置未改变，只是插件版本不同

**Comment by morytyann** [comment]
应该是修复#103导致的

**Comment by morytyann** [comment]
我先关闭了，因为修不了……

**Comment by morytyann** [comment]
有点道理，但不多，我觉得还是先这样吧，毕竟内存还能从其他地方看，匹配不了是真匹配不了

我再找找有没有其他办法

**Comment by morytyann** [comment]
我也是不开的匹配的，但是有的人会把路由器当作轻NAS，用于下载和提供服务，如果不支持匹配进程，那就很麻烦了
