### ISSUE TITLE
请问如何解析IPV6地址？

### ISSUE THREAD

**Issue by xgytao** [morytyann/OpenWrt-mihomo#115]
开了mihomo后，覆盖 Fake-IP 过滤列表加入的域名 网络诊断里nslookup还是解析不出ipv6地址来。
IPv6 DNS 劫持 我点了勾选
IPv6 代理 这个勾选就不能上网了
[DNS 配置] ipv6 勾选不勾选一样没用

---

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: true
  sniff:
    HTTP:
      override-destination: true
      ports:
        - 80
        - 8080-8880
    TLS:
      override-destination: true
      ports:
        - 443
        - 8443
    QUIC:
      override-destination: true
      ports:
        - 443
        - 8443
proxy-providers:
  cf:
    type: file
    path: "./cf.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  euserv:
    type: file
    path: "./euserv.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  serv00:
    type: file
    path: "./serv00.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  hax:
    type: file
    path: "./hax.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: "\U0001F680节点选择"
    type: select
    disable-udp: false
    proxies:
      - "♻️自动选择"
    use:
      - cf
      - euserv
      - serv00
      - hax
  - name: "♻️自动选择"
    type: url-test
    disable-udp: false
    use:
      - cf
      - euserv
      - serv00
      - hax
    url: http://www.gstatic.com/generate_204
    interval: '300'
    tolerance: '50'
  - name: "\U0001F4F2电报"
    type: select
    disable-udp: false
    proxies:
      - "\U0001F680节点选择"
      - DIRECT
    use:
      - cf
      - euserv
      - serv00
      - hax
  - name: "\U0001F4F9油管"
    type: select
    disable-udp: false
    proxies:
      - "\U0001F680节点选择"
      - DIRECT
    use:
      - cf
      - euserv
      - serv00
      - hax
  - name: "\U0001F4E2谷歌"
    type: select
    disable-udp: false
    proxies:
      - "\U0001F680节点选择"
      - DIRECT
    use:
      - cf
      - euserv
      - serv00
      - hax
  - name: "Ⓜ️微软"
    type: select
    disable-udp: false
    proxies:
      - "\U0001F680节点选择"
      - DIRECT
    use:
      - cf
      - euserv
      - serv00
      - hax
  - name: "\U0001F54A推特"
    type: select
    disable-udp: false
    proxies:
      - "\U0001F680节点选择"
      - DIRECT
    use:
      - cf
      - euserv
      - serv00
      - hax
rule-providers:
  自定义代理:
    type: file
    behavior: classical
    path: "./rules/自定义代理.yaml"
    format: yaml
  自定义直连:
    type: file
    behavior: classical
    path: "./rules/自定义直连.yaml"
    format: yaml
  自定义拦截:
    type: file
    behavior: classical
    path: "./rules/自定义拦截.yaml"
    format: yaml
rules:
  - "RULE-SET,自定义拦截,REJECT"
  - "geosite,microsoft,Ⓜ️微软"
  - "geosite,youtube,\U0001F4F9油管"
  - "geosite,telegram,\U0001F4F2电报"
  - "geoip,telegram,\U0001F4F2电报"
  - "geosite,twitter,\U0001F54A推特"
  - "geoip,twitter,\U0001F54A推特"
  - "geosite,google,\U0001F4E2谷歌"
  - "geoip,google,\U0001F4E2谷歌"
  - "RULE-SET,自定义代理,\U0001F680节点选择"
  - "RULE-SET,自定义直连,DIRECT"
  - "geoip,private,DIRECT"
  - "geosite,cn,DIRECT"
  - "geoip,cn,DIRECT"
  - "MATCH,\U0001F680节点选择"
mode: rule
find-process-mode: off
unified-delay: false
tcp-concurrent: false
keep-alive-interval: 600
log-level: info
ipv6: false
external-ui: ui
external-controller: 0.0.0.0:9090
secret: 961232
profile:
  store-selected: true
  store-fake-ip: true
allow-lan: true
port: 8080
socks-port: 1080
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
tun:
  stack: mixed
  device: tun
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
  enable: true
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  use-system-hosts: false
  use-hosts: false
  nameserver-policy:
    geosite:cn,private:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    geosite:geolocation-!cn:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
  fake-ip-filter:
    - +.lan
    - +.local
    - vpn域名
geodata-mode: true
geodata-loader: standard
geox-url:
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 168
interface-name: pppoe-wan
authentication:
  - mihomo:961232
hosts:
  localhost:
    - 127.0.0.1
    - ::1
  sp.cesu.eu.org:
    - 104.19.250.155
    - 104.16.113.213

**Comment by morytyann** [comment]
Fake-IP模式就是只能解析出Fake-IP，你可以换Redir-Host

**Comment by morytyann** [comment]
哦你添加了Fake-IP过滤列表，你可以试试直接运行核心，nslookup指定服务器试试解析结果，如果还是没有IPv6结果那就是核心的问题了

**Comment by morytyann** [comment]
我试了，知道是什么问题了，不开启IPv6代理的时候我会把配置文件里[IPv6](https://wiki.metacubex.one/config/general/#ipv6)关掉，文档里写的是`是否允许内核接受 IPv6 流量`，但实际行为不止是这样，还会屏蔽AAAA记录……我改一下吧

**Comment by morytyann** [comment]
一会更新到v1.7.2就好了
