### ISSUE TITLE
[BUG] PKG_RELEASE数值设置问题

### ISSUE THREAD

**Issue by ForestL18** [morytyann/OpenWrt-mihomo#119]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt 23.05.3 r27917-81a1f98d5b

### 插件版本

1.7.1

### 硬件架构

aarch64_generic

### BUG 描述

`mihomo/Makefile`中的`PKG_RELEASE:=1`感觉还是不能改，否则上个版本你把这个值改成了2，这个版本被重置成了1，直接使用opkg升级软件包的话会提示无法降级。

### 预期行为

无

### 复现步骤

无

### 插件配置

无

**Comment by morytyann** [comment]
我改一下

但是我得说一下：
1. 版本比较和`PKG_RELEASE`无关，只比较`PKG_VERSION`
2. 如果不设置`PKG_VERSION`它会根据`PKG_SOURCE_DATE`和`PKG_SOURCE_VERSION`生成
3. 因为我想让他生成`PKG_VERSION`，且和核心的`Version`一致，所以我给`PKG_SOURCE_DATE`设置了alpha，这样生成出来就是`alpha-xxxxxxxx`这种格式的了，当时没想到会有这个问题

**Comment by morytyann** [comment]
我修改了Makefile，将`PKG_SOURCE_DATE`设置为日期，Workflow也一并改了，UTC时间0点自动获取，然后将`PKG_SOURCE_DATE`设置为昨天

**Comment by morytyann** [comment]
嗯嗯，你说得对，我表述有问题，我想说的是`PKG_VERSION`不同时不会比较`PKG_RELEASE`，感谢勘误❤️

**Comment by morytyann** [comment]
@ForestL18 #123 建了个群，通知你一下
