### ISSUE TITLE
[Feature Request] 建议作者把插件名字改成一个单词

### ISSUE THREAD

**Issue by pmkol** [morytyann/OpenWrt-mihomo#122]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

建议改成一个单词，不然会导致一些路由器界面，左侧菜单栏显示成两行

**Comment by morytyann** [comment]
会吗，我试了基本都可以可以放开，难道是显示器区别导致的？

**Comment by pmkol** [comment]
> 会吗，我试了基本都可以放开，难道是显示器区别导致的？

笔记本开了缩放的话，会导致两行显示的

**Comment by morytyann** [comment]
我想起有个解锁网易云音乐的插件，它的名字也很长，搞得我强迫症犯了，我也不想换行，所以我还在几个主题上都测了一遍，看着没问题了我才决定用这个的

**Comment by morytyann** [comment]
你换个主题试试看，我不想改了，这个挺好的，而且我也不想改成`OpenMihomo`，我不喜欢蹭热度🥲

**Comment by pmkol** [comment]
> 我想起有个解锁网易云音乐的插件，它的名字也很长，搞得我强迫症犯了，我也不想换行，所以我还在几个主题上都测了一遍，看着没问题了我才决定用这个的

笔记本尤其是14寸以下的，要开系统DPI缩放，这个缩放会导致字体变大换行，每个屏幕的缩放比可能不一样，就会导致这个问题，我看到讨论里你也给出了4个名字，为什么不从那4个名字里选一个呢

**Comment by morytyann** [comment]
那我改成`OriginProxy`？缩写成`OP`会不会和`OpenWrt`混淆呢？

**Comment by pmkol** [comment]
> Referenc

那直接改成MihomoProxy不就好了，无歧义还容易理解

**Comment by morytyann** [comment]
加个T吧，MihomoTProxy，也挺长的，你试试你那里可以不换行吗，修改`/usr/share/luci/menu.d/luci-app-mihomo.json`

**Comment by morytyann** [comment]
不加也行，你试试

**Comment by churdes** [comment]
+1，我也觉得一个单词好一些，精简。可以起个好名字

**Comment by pmkol** [comment]
> MihomoTProxy

试了，两个都没问题

**Comment by morytyann** [comment]
所以你为什么不早去讨论里提呢，我改了你才来😭

**Comment by pmkol** [comment]
> 所以你为什么不早去讨论里提呢，我改了你才来😭

因为没看到，我自己fork的时候才发现 QAQ

**Comment by pmkol** [comment]
> 所以你为什么不早去讨论里提呢，我改了你才来😭

作者搞个TG群如何，更适合讨论插件问题

**Comment by morytyann** [comment]
> 作者搞个TG群如何，更适合讨论插件问题

可以，等开通了踢你一下

**Comment by zutzo** [comment]
PureMihomo 怎么样（）

**Comment by morytyann** [comment]
> PureMihomo 怎么样（）

@zutzo 晚辣😭

**Comment by morytyann** [comment]
@pmkol #123
