### ISSUE TITLE
[Feature Request]請問可以增加還原默認設置的開關嗎?

### ISSUE THREAD

**Issue by op741946** [morytyann/OpenWrt-mihomo#126]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

在openclash有這樣的開關，不知道作者會不會新增?
![00](https://github.com/user-attachments/assets/096cd666-54dc-4d5d-b908-dee635648157)

**Comment by morytyann** [comment]
没有意向，没有做这个功能的必要。

如果你想重置的话：
1. 卸载后删除`/etc/config/mihomo`文件，然后重新安装。
2. 用仓库的mihomo.conf覆盖掉`/etc/config/mihomo`（需要确保版本一致，可以从TAG那里选历史版本的源码然后下载）。

感谢Issue。

**Comment by op741946** [comment]
好的，謝謝您!
