### ISSUE TITLE
无法识别替换内核版本

### ISSUE THREAD

**Issue by xyself** [morytyann/OpenWrt-mihomo#138]
内核版本建议作为mihomo metacubexd这种形式可以随意下载替换。

**Comment by xyself** [comment]
如同openclash 中的内核随意替换mihomo的任意版本，想请问mihomo的内核为什么要经过二次编译

**Comment by zutzo** [comment]
> 内核版本建议作为mihomo metacubexd这种形式可以随意下载替换。

> 如同openclash 中的内核随意替换mihomo的任意版本，想请问mihomo的内核为什么要经过二次编译

提问前您是否翻阅过 已存在的 issue https://github.com/morytyann/OpenWrt-mihomo/issues/87 https://github.com/morytyann/OpenWrt-mihomo/issues/65
