### ISSUE TITLE
[Feature Request] 希望可以添加手动上传UI文件和GeoX文件

### ISSUE THREAD

**Issue by lsy0xcc** [morytyann/OpenWrt-mihomo#146]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

有些网络环境特别恶劣的地方，大部分github镜像站都被屏蔽了，所以会导致GeoX下载失败无法启动，也没有办法下载metacubeXD这种UI控制台去调路由器的节点。这样就是“必须要路由器走代理才能下载文件->必须下载文件才能让路由器走代理”的死锁了，希望可以手动上传来避开这个死锁。感谢作者大大~

### 如何实现

![image](https://github.com/user-attachments/assets/8a84305d-775f-43fa-8d3a-37024f9397f1)
![image](https://github.com/user-attachments/assets/ab2e9e25-7b37-4e58-9ead-a4b89e3fdafb)
如果可以在这里添加几个类似上传配置文件的表单就好了吧（前端切图仔没法帮助作者大大做贡献了，对不起

**Comment by zutzo** [comment]
我认为应当手动上传到 `/etc/mihomo/run` 目录下
不必多加按钮

**Comment by morytyann** [comment]
1. 面版可以用[公网](https://metacubex.github.io/metacubexd/#/setup)的，调一下网站设置，允许不安全的内容就能连了
2. GeoX文件不好下两个办法，一是用SFTP软件上传，二是别用GeoIP/GeoSite的规则（这样不需要下载）

上传按钮就不加了，感谢Issue。❤️
