### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by armin19900** [morytyann/OpenWrt-mihomo#147]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

希望能更新下[订阅转换配置]--模板  那些规则。
ACL4SSR--Twitter（X）是走 漏网之鱼。。最新的是有更新X网址走节点的。

**Comment by zutzo** [comment]
@armin19900 @morytyann 该动刀了 不然就晚了

**Comment by morytyann** [comment]
你可以自行填写你说的新的模板的地址……或者使用第三方的WEB UI，例如品云、dler，看有没有你想要的模板

P.S. 我早晚砍掉它（订阅转换）😑
