### ISSUE TITLE
[BUG]更新最新版本以后，面板上内存的显示不正常

### ISSUE THREAD

**Issue by qaz69** [morytyann/OpenWrt-mihomo#152]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

OpenWrt

### 系统版本

22.03.03

### 插件版本

最新版本

### 硬件架构

x86_64

### BUG 描述

如题
![IMG_20240901_113545](https://github.com/user-attachments/assets/48379376-582d-4ea4-ba8e-0cd378380ece)

### 预期行为

无

### 复现步骤

打开面板

### 插件配置

跟配置无关

**Comment by zutzo** [comment]
https://github.com/morytyann/OpenWrt-mihomo/issues/113 与 重复

**Comment by zh15933** [comment]
https://github.com/morytyann/OpenWrt-mihomo/issues/113#issuecomment-2308011079

**Comment by qaz69** [comment]
谢谢以上大佬提示
