### ISSUE TITLE
[BUG] Choose Profile is NOT optional

### ISSUE THREAD

**Issue by honwen** [morytyann/OpenWrt-mihomo#153]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

23.05.3

### 插件版本

v1.7.6

### 硬件架构

aarch64_cortex-a53

### BUG 描述

https://github.com/morytyann/OpenWrt-mihomo/blob/v1.7.6/luci-app-mihomo/htdocs/luci-static/resources/view/mihomo/editor.js#L25

`o.optional = true;` **seems not working**

![image](https://github.com/user-attachments/assets/ed4efbcd-166f-4cc5-9c5a-cc3cc6fba139)

### 预期行为

Choose Profile is `optional`

### 复现步骤

null

### 插件配置

null

**Comment by zutzo** [comment]
@honwen 不选择配置 那么启动的意义是？

**Comment by morytyann** [comment]
I don't know what you're talking about, did you want to start without any profile? You can just upload and select an empty file.

**Comment by morytyann** [comment]
你发的是编辑器页的[代码](https://github.com/morytyann/OpenWrt-mihomo/blob/v1.7.6/luci-app-mihomo/htdocs/luci-static/resources/view/mihomo/editor.js#L25)，不是配置页的[代码](https://github.com/morytyann/OpenWrt-mihomo/blob/v1.7.6/luci-app-mihomo/htdocs/luci-static/resources/view/mihomo/config.js#L157)，配置页就是必填项，你看错了

**Comment by honwen** [comment]
相关配置通过： `用于混入的文件`

没必要是必填项

**Comment by honwen** [comment]
另外一个BUG：
`geoip-code` 不是list
https://github.com/MetaCubeX/mihomo/blob/v1.18.7/docs/config.yaml#L288

这里全当list了
https://github.com/morytyann/OpenWrt-mihomo/blob/v1.7.6/mihomo/files/mihomo.init#L514

**Comment by morytyann** [comment]
> 相关配置通过： `用于混入的文件`
> 
> 没必要是必填项

不会改，改了绝对会有人来提：此处应该改成必填项。

> `geoip-code` 不是list

这个UI改不了，TableSection只能要么都是列表，要么都是输入框，不过现在也不建议使用fallback-nameserver了，趁早改成nameserver-policy吧，这个就不修了。
