### ISSUE TITLE
[Feature Request]定时/手动更新订阅，而不是每次启动的时候下载

### ISSUE THREAD

**Issue by undoubted** [morytyann/OpenWrt-mihomo#154]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

每次启动的时候下载，既浪费资源也没有必要，还增加了启动的时间等开销

**Comment by zutzo** [comment]
@undoubted 上传/截图 所有 日志

**Comment by morytyann** [comment]
呃……重启时下不下来，手动/定时更新就可以下下来了吗？

**Comment by undoubted** [comment]
解析到ipv4就可以下载了。。。

只是举个例子，并不需要每次都下载，按需更新就可以了。
如果碰到我这种ipv6不能下载，ipv4可以的情况，就很不方便调试

**Comment by morytyann** [comment]
我觉得你应该解决IPv6无法下载的问题

[XY Problem](https://en.wikipedia.org/wiki/XY_problem)

**Comment by undoubted** [comment]
问题描述已改。

解决IPv6无法下载问题的确是一种方法。

提供更健壮的程序也是一种方法。期待更新

**Comment by morytyann** [comment]
现在的手动/定时重启已经满足了你的手动/定时更新订阅的需求。

你觉得每次下载既浪费资源也没有必要，首先你没说清楚，浪费了什么资源，为什么没有必要。其次，有的人觉得这是优点，每次启动都能保证是最新的。

还有就是，如果修改了插件里订阅配置的内容（如链接、订阅转换选项等），保存并应用后，插件没办法得知的，如果改成手动更新，这时需要用户手动更新后才能使用使用新的内容。

至于增加启动时间，目前插件启动很快，下载订阅也绝对不占启动时间的大头，我认为是可以接受的。

**Comment by morytyann** [comment]
每次下载订阅的时间过长，我可以设置个超时时间，超时退出就好了。

**Comment by zutzo** [comment]
建议把下载订阅也砍了，如果不想遇到这个问题自己写配置文件
https://wiki.metacubex.one/config/proxy-providers/  把 interval 参数调为0

**Comment by undoubted** [comment]
> 现在的手动/定时重启已经满足了你的手动/定时更新订阅的需求。
> 
> 你觉得每次下载既浪费资源也没有必要，首先你没说清楚，浪费了什么资源，为什么没有必要。其次，有的人觉得这是优点，每次启动都能保证是最新的。
> 
> 还有就是，如果修改了插件里订阅配置的内容（如链接、订阅转换选项等），保存并应用后，插件没办法得知的，如果改成手动更新，这时需要用户手动更新后才能使用使用新的内容。
> 
> 至于增加启动时间，目前插件启动很快，下载订阅也绝对不占启动时间的大头，我认为是可以接受的。

在调试/配置阶段，重启的间隔可能是几秒，如果每几秒都要重新下载一次，无疑是没有必须要的。

如果有人需要每次都重新下载，完全可以做成配置项。

更多的人应该是需要稳定的配置，而不是每次重启都有可能因为订阅变化发生改变，甚至配置错误启动失败，造成不可用。

修改订阅配置后自动重启插件也是可以做到的，保存后判断是否是当前使用的订阅，是就下载/重启。

**Comment by undoubted** [comment]
PS. ipv6下载问题已经通过更换只有ipv4解析的subconveter解决了。

PS2. 手动/定时更新订阅更符合人们对订阅功能的理解或认知。

**Comment by zutzo** [comment]
> 更多的人应该是需要稳定的配置，而不是每次重启都有可能因为订阅变化发生改变，甚至配置错误启动失败，造成不可用。

前面已经说过了 自己写配置文件 [proxy-providers](https://wiki.metacubex.one/config/proxy-providers/) 填机场 想咋更新咋更新

wiki 甚至提供了完整的配置供你快捷使用

用订阅转换是非必要的 

> PS2. 手动/定时更新订阅更符合人们对订阅功能的理解或认知。
至于这个

还是砍了吧 
~屁事这么多~

**Comment by morytyann** [comment]
> 在调试/配置阶段，重启的间隔可能是几秒，如果每几秒都要重新下载一次，无疑是没有必须要的。

那你完全可以先下载下来，使用文件来调试，调试完了在切换成订阅，反正短时间内你都是在"调试"，内容不会变更。

> 手动/定时更新订阅更符合人们对订阅功能的理解或认知

思路问题，没有什么好说的，我已经提示过启动会下载文件了，。

我不想再回答了，关掉了。

**Comment by undoubted** [comment]
哈哈，大家别破防啊，提个需求不至于
