### ISSUE TITLE
[Feature Request]增加备份功能，openwrt系统升级不丢失资源文件

### ISSUE THREAD

**Issue by Joee-D** [morytyann/OpenWrt-mihomo#157]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

当前openwrt升级系统时不会备份/etc/mihomo路径，资源文件会丢失
如果上传自定义配置文件到/etc/mihomo/profile下，升级后配置文件会丢失，导致无法启动，需要重新上传文件
其他网络文件虽然可以自动下载，但是会带来不必要开销

规避方法：在 系统-备份与升级-配置中手动添加/etc/mihomo路径

### 如何实现

增加/etc/mihomo或者至少增加/etc/mihomo/profile 到/lib/upgrade/keep.d/*下

参考openclash实现：
https://github.com/vernesong/OpenClash/blob/dd5e07d891f12ab46830db4064f7a0e19a08f38d/luci-app-openclash/root/etc/uci-defaults/luci-openclash#L45

参考官方文档：
https://openwrt.org/docs/techref/sysupgrade

**Comment by morytyann** [comment]
在 https://github.com/morytyann/OpenWrt-mihomo/commit/8fb7fff0f06738275be8452b82e8329cce2e171a 处理了
