### ISSUE TITLE
[Feature Request] 支持混入配置 `fake-ip-filter-mode`

### ISSUE THREAD

**Issue by SharerMax** [morytyann/OpenWrt-mihomo#158]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

在混入配置中可切换 fakeip 的匹配模式
https://github.com/MetaCubeX/mihomo/blob/43f21c0b412b7a8701fe7a2ea6510c5b985a53d6/docs/config.yaml#L252-L254

### 如何实现

在 混入配置 -> DNS 配置 tab 页 新增选项 `fakeIp 过滤模式`下拉菜单(对应`mihomo` 的`dns.fake-ip-filter-mode`)，菜单选项分别为`黑名单`和`白名单`，对应值分别为 `blacklist` 和 `whitelist`

**Comment by morytyann** [comment]
先用着混入文件吧，内容这样写：

```yaml
dns:
  fake-ip-filter-mode: blacklist
```
