### ISSUE TITLE
[BUG]开启服务后，无法连接 wireguard

### ISSUE THREAD

**Issue by sean-root** [morytyann/OpenWrt-mihomo#160]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

OpenWrt

### 系统版本

23.05.4

### 插件版本

1.7.6

### 硬件架构

x86_64

### BUG 描述

开启服务后，无法连接 wireguard

### 预期行为

期望开启服务后，可以连接 wireguard

### 复现步骤

开启服务后，无法连接 wireguard

### 插件配置

开启服务后，无法连接 wireguard

**Comment by zutzo** [comment]
截图？日志？你是一个不发啊

**Comment by sean-root** [comment]
哈哈，实在抱歉，主要是我查询了下日志，里面也没有 wireguard 相关的内容，wireguard 虚拟了一个网络接口吧（我理解）

看了下wireguard的接口数据，发送/接受都是0，关掉 mihomo 服务，就可以了，使用 openclash 倒是没有什么问题。mihomo在 tproxy / tun 下都是了，下面的选项几乎每一个都尝试了，也不行

**Comment by morytyann** [comment]
我这里是可以的……需要更多的信息
![image](https://github.com/user-attachments/assets/35c260c6-76c6-4863-bb75-2659384e2113)
![image](https://github.com/user-attachments/assets/f46cdfea-bb86-4670-9103-8b56fb99ea48)

**Comment by sean-root** [comment]
求一个配置界面的截图

**Comment by morytyann** [comment]
插件吗？基本是默认配置。

你看看 代理配置 绕过 wan/wan6接口 对吗？

**Comment by sean-root** [comment]
> 插件吗？基本是默认配置。
> 
> 你看看 代理配置 绕过 wan/wan6接口 对吗？

找到原因了，是 wireguard 的端口和 mihomo 冲突产生的 “reject loopback connection”，绕过 wireguard udp 通道端口就可以了，比如 200，我这么写的：1-199, 201-65536

这样写看着挺恶心的，有没有其他的解决方法？绕过的 wan / wan6 里，我也尝试加上 wireguard 接口了，也不行。

当然，把 “绕过中国大陆IP” 钩上也是可以的（但不想这么做）

除了这样写绕过 udp 端口外，求问现在有没有稍微优雅点的解决方法？

**Comment by morytyann** [comment]
为何会冲突，你的WireGuard是怎么配的？

我没有做任何特殊配置，只放开了51820端口，完全可以正常连接的。

**Comment by morytyann** [comment]
更新到v1.7.8再试试。

**Comment by sean-root** [comment]
WireGuard 没做特殊的配置工作，只放行了端口号，好的，今天回家试试，现在不敢试，不然就连不上家里网络了，代理绕过配置如下：

<img width="473" alt="image" src="https://github.com/user-attachments/assets/0faf64b7-acc0-4bf8-9459-dd07a0c74c71">

**Comment by sean-root** [comment]
> 更新到v1.7.8再试试。

更新到 v1.7.8 以后，把要代理的端口改回 “全部端口”，也没有任何问题了～ 👍 但还是稀里糊涂不知道啥原因 😅
