### ISSUE TITLE
[BUG]all architectures failed, maybe release is still in building, or just miss/unsupport your arch

### ISSUE THREAD

**Issue by mmmjie** [morytyann/OpenWrt-mihomo#165]
### 自查步骤

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、节点信息等敏感信息

### 系统

OpenWrt

### 系统版本

6.6.30

### 插件版本

还没装

### 硬件架构

aarch64_cortex-a53

### BUG 描述

root@OpenWrt:~# curl -s -L https://raw.githubusercontent.com/morytyann/OpenWrt-mihomo/main/install.sh | ash
aarch64_cortex-a53: start
aarch64_cortex-a53: download tarball
aarch64_cortex-a53: extract tarball
aarch64_cortex-a53: install ipks
all architectures failed, maybe release is still in building, or just miss/unsupport your arch

安装不了

### 预期行为

希望能成功安装

### 复现步骤

直接使用命令

### 插件配置

![image](https://github.com/user-attachments/assets/b663e0b9-a5fd-433b-af55-3645ee5d76e0)

### 配置文件

无

### 插件日志

无

### 核心日志

无

**Comment by zutzo** [comment]
@mmmjie opkg print-architecture 
输入这个显示什么呢？

**Comment by mmmjie** [comment]
> @mmmjieopkg print-architecture 输入这个显示文件？

root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10

**Comment by zutzo** [comment]
@mmmjie 手动上传安装会显示什么报错？
