### ISSUE TITLE
[BUG]直连direct不显示延迟，只有代理节点显示延迟

### ISSUE THREAD

**Issue by caserangle** [morytyann/OpenWrt-mihomo#169]
### 自查步骤

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、节点信息等敏感信息

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt SNAPSHOT r31093-2ac4c65f74 / LuCI Master 24.198.17579~d8fcaea

### 插件版本

1.8.0

### 硬件架构

aarch64_cortex-a53

### BUG 描述

策略组里的直连direct节点无法显示延迟，延迟测速地址是 https://www.gstatic.com/generate_204， 我最初以为是我的配置文件，但尝试了OP和电脑的verge软件，direct都是正常显示延迟的，而且直连也是没问题的。所以想问下如何解决。是我需要改什么吗
![屏幕截图 2024-09-07 075647](https://github.com/user-attachments/assets/fc7330ea-08be-49f6-a1e8-325e5ae6c8dd)

### 预期行为

无

### 复现步骤

面板里测速就会这么显示

### 插件配置

无

### 配置文件

[寒冰改版.zip](https://github.com/user-attachments/files/16913746/default.zip)

### 插件日志

无

### 核心日志

无

**Comment by caserangle** [comment]
尝试将测速链接换成1.1.1.1就有延迟了，但超高110多MS
![屏幕截图 2024-09-07 084704](https://github.com/user-attachments/assets/b7f8f688-88c7-4ee9-8da3-74a08e229076)

**Comment by zutzo** [comment]
换测试链接能通就说明是测试链接问题

**Comment by caserangle** [comment]
但一点不解是的为何直连延迟应该显示最低吧，如果是因为本身直连距离测速地址距离比proxy更远，那其他类似clash软件是对direct测速采取了不同形式的策略吗。因为其他类似ios stash或者openclash还有电脑的verge，对于同样的配置文件，他们的direct统一延迟开启都是最低的。

**Comment by zutzo** [comment]
@caserangle 换别的试试

https://imldy.cn/posts/99d42f85/

我没在这方面深究

**Comment by caserangle** [comment]
好的 感谢作者回复我再研究下 先关闭issues了
