### ISSUE TITLE
代理异常

### ISSUE THREAD

**Issue by luestr** [morytyann/OpenWrt-mihomo#18]
半小时前的编译包更新后，一些特定的网站无法打开，如 google.com youtube.com，但是却可以打开 x.com github.com 等网站

日志中找到很多此类错误，不确定是否与此有关。
```
time="2024-06-27T07:40:32.902092952Z" level=debug msg="[Process] find process 91.108.56.134 error: process not found"
time="2024-06-27T07:40:32.903067377Z" level=debug msg="[Process] find process 91.108.56.134 error: process not found"
time="2024-06-27T07:40:32.903372334Z" level=debug msg="[Process] find process 91.108.56.134 error: process not found"
time="2024-06-27T07:40:32.903805775Z" level=debug msg="[Process] find process 91.108.56.134 error: process not found"
```

已通过iOS代理工具排除节点问题
<img width="609" alt="Snipaste_2024-06-27_15-48-11" src="https://github.com/morytyann/OpenWrt-mihomo/assets/152216177/5b3d2028-55db-40ba-b20b-7b53e3f35d00">

<img width="805" alt="Snipaste_2024-06-27_15-48-19" src="https://github.com/morytyann/OpenWrt-mihomo/assets/152216177/16fa29bb-cab7-4c1d-ae42-93dc31d0562c">

**Comment by morytyann** [comment]
修改配置文件，`find-process-mode: off`，再试试

**Comment by morytyann** [comment]
电脑有IPv6的DNS吗？

**Comment by morytyann** [comment]
目前只劫持了IPv4的DNS请求，如果你需要IPv6但是又想使用本插件的话，目前的workaround是不下发IPv6的DNS服务器
`接口 > 编辑lan接口 > DHCP服务器 > IPv6设置 > 取消勾选本地 IPV6 DNS 服务器`
这样并不会影响IPv6的使用，因为IPv4的DNS也可以返回AAAA的记录
