### ISSUE TITLE
请教大佬们，公网通过域名打开控制面板如何设置？

### ISSUE THREAD

**Issue by drw2005** [morytyann/OpenWrt-mihomo#189]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

是我没设置好吗，公网打不开控制面板。
以前用OpenClash，可以通过防火墙里的端口转发，再配合OpenClash里的“外部控制设置”，就可以直接从公网打开控制面板了。

### 如何实现

能否象OpenClash一样，外部控制配置里增加类似“管理页面公网域名”、“管理页面映射端口”等功能，配合端口转发，实现公网访问。

**Comment by jimmieyangcsjs** [comment]
我猜是在软路由本地网络无法用ddns的域名访问，使用IP地址访问正常
但是在外网 或者代理网络下可以用ddns的域名访问。

**Comment by drw2005** [comment]
> 测试正常，无论是端口转发还是放行。
> 
> 你是如何配置的？

不好意思，现在正常了。
是我的端口转发写错了，麻烦大佬了。
