### ISSUE TITLE
大佬，请问一下能不能加一个可以直接编辑配置文件的页面？

### ISSUE THREAD

**Issue by 350048663** [morytyann/OpenWrt-mihomo#22]
大佬，请问一下能不能加一个可以直接编辑配置文件的页面？由于我用的GFW模式，有时候要加一些东西比较方便

**Comment by morytyann** [comment]
这个功能优先级比较低，暂时不会添加，等一等吧
建议先用Xftp之类的软件直接编辑，保存后运行`service mihomo restart`即可

**Comment by morytyann** [comment]
通过 #25 添加了配置文件的监控，[详见](https://github.com/morytyann/OpenWrt-mihomo/issues/24#issuecomment-2210627827)

**Comment by morytyann** [comment]
在你的PR #26 基础上，我添加了可以选择配置文件的功能，感谢PR

**Comment by 350048663** [comment]
> 在你的PR #26 基础上，我添加了可以选择配置文件的功能，感谢PR
感谢大佬，添加了我想要的功能😃
