### ISSUE TITLE
添加重启按钮

### ISSUE THREAD

**Issue by zutzo** [morytyann/OpenWrt-mihomo#24]
修改配置后需要在 luci 界面进行 `关闭-应用-开启-应用` 操作略麻烦
希望可以加一个 `手动重启` 的按钮

**Comment by morytyann** [comment]
不需要呀，如果是修改LuCI配置项直接修改配置后应用就可以了，不过某些配置（例如接口密钥）可能无法直接生效。
你是直接修改文件吗？

**Comment by morytyann** [comment]
添加了配置文件的监控，当当前配置文件的内容修改后，会自动重载。
这样即使你直接修改配置文件也不用手动按重启按钮了。

**Comment by 350048663** [comment]
> 添加了配置文件的监控，当当前配置文件的内容修改后，会自动重载。 这样即使你直接修改配置文件也不用手动按重启按钮了。

监控的是run里面的配置文件？还是profiles里的配置文件？

**Comment by morytyann** [comment]
profiles里的
________________________________
发件人: Nightdog ***@***.***>
发送时间: Friday, July 5, 2024 9:14:53 PM
收件人: morytyann/OpenWrt-mihomo ***@***.***>
抄送: Joseph Mory ***@***.***>; State change ***@***.***>
主题: Re: [morytyann/OpenWrt-mihomo] 添加重启按钮 (Issue #24)


添加了配置文件的监控，当当前配置文件的内容修改后，会自动重载。 这样即使你直接修改配置文件也不用手动按重启按钮了。

监控的是run里面的配置文件？还是profiles里的配置文件？

―

**Comment by 350048663** [comment]
> profiles里的
![f4b8121d3311b17f93f4027b8ba35508](https://github.com/morytyann/OpenWrt-mihomo/assets/60809507/fe333227-f46e-4afd-a887-84b04e564709)
我加了个编辑页面可以PR吗？（只能编辑固件文件config.yaml）

**Comment by morytyann** [comment]
编辑这个文件没有意义呀，重启插件后会被覆盖了

**Comment by 350048663** [comment]
> @350048663 编辑这个文件没有意义呀，重启插件后会被覆盖了

我编辑的是profiles里的配置文件，不是run里的，应该不会被覆盖吧？

**Comment by morytyann** [comment]
> > @350048663 编辑这个文件没有意义呀，重启插件后会被覆盖了
> 
> 我编辑的是profiles里的配置文件，不是run里的，应该不会被覆盖吧？

抱歉看错了路径，你提PR吧

**Comment by morytyann** [comment]
已添加。
