### ISSUE TITLE
[Feature Request] 本地代理端口是什么？

### ISSUE THREAD

**Issue by Masterchef2000** [morytyann/OpenWrt-mihomo#245]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

我在ubuntu上安装了deb版本的mihomo party，安装配置代理后，浏览器可正常使用代理，我想在终端使用代理，配置命令为export http_proxy="http://127.0.0.1:port" 尝试过7890端口发现无效，应该怎么配置？

**Comment by JohnsonRan** [comment]
@Masterchef2000 这是MTP项目 来错地方了吧
