### ISSUE TITLE
[BUG]Cloudflare的自建Worders和Pages节点（CF免费自建Vless节点）无法使用

### ISSUE THREAD

**Issue by meteorain** [morytyann/OpenWrt-mihomo#246]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### 系统版本

23.05.4

### 插件版本

1.8.7-1

### 核心版本

2024.10.19~95af5f73-r1

### 硬件架构

aarch64_cortex-a53

### BUG 描述

![image](https://github.com/user-attachments/assets/267664e9-2bc9-48eb-ad37-9aa3b4efa4f2)
我的服务器里有几个节点，CF开头的三个是Cloudflare上的自建Workers节点或Pages节点，SB开头的是AWS EC2自建节点。
最近路由器上换了mihomo，发现CF的自建节点（使用网上的js脚本搭建，比如这个：https://github.com/meteorain/EDtunnel）不能正常使用，而这几个节点在安卓上的Clash Meta、Karing，和路由器上的OpenClash和ShellClash上是可以正常使用的。

### 预期行为

CF自建Workers或Pages节点可以在mihomo上使用。

### 复现步骤

使用网上的js脚本搭建，比如这个：https://github.com/meteorain/EDtunnel 或 https://github.com/EDtunnel-rev/EDtunnel-rev，5分钟可以自建一个CF免费节点。节点导入到mihomo中，尝试各种配置组合，都无法使用CF的节点。

### 插件配置

mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='1'
mihomo.config.cron_expression='0 3 * * 3'
mihomo.config.profile='subscription:subscription'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.fast_reload='0'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.tcp_transparent_proxy_mode='redirect'
mihomo.proxy.udp_transparent_proxy_mode='tun'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='1'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='1'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='all'
mihomo.proxy.bypass_china_mainland_ip='0'
mihomo.proxy.acl_tcp_dport='0-65535'
mihomo.proxy.acl_udp_dport='0-65535'
mihomo.subscription=subscription
mihomo.subscription.name='xxx.xxx.com'
mihomo.subscription.url='https://xxx.xxx.com/meta.yml'
mihomo.subscription.user_agent='clash.meta'
mihomo.mixin=mixin
mihomo.mixin.log_level='warning'
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.ipv6='1'
mihomo.mixin.tcp_keep_alive_idle='600'
mihomo.mixin.tcp_keep_alive_interval='15'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9999'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='1'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='1'
mihomo.mixin.tun_stack='mixed'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='fake-ip'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='1'
mihomo.mixin.dns_respect_rules='0'
mihomo.mixin.dns_doh_prefer_http3='0'
mihomo.mixin.dns_ipv6='1'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='1'
mihomo.mixin.hosts='0'
mihomo.mixin.dns_nameserver='0'
mihomo.mixin.dns_nameserver_policy='0'
mihomo.mixin.geoip_format='dat'
mihomo.mixin.geodata_loader='memconservative'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='1'
mihomo.mixin.geox_update_interval='72'
mihomo.mixin.api_secret='xueyuhappy'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='138449'
mihomo.@host[0]=host
mihomo.@host[0].enabled='0'
mihomo.@host[0].domain_name='localhost'
mihomo.@host[0].ip='127.0.0.1' '::1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='direct-nameserver'
mihomo.@nameserver[2].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='1'
mihomo.@nameserver[3].type='nameserver'
mihomo.@nameserver[3].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[4]=nameserver
mihomo.@nameserver[4].enabled='0'
mihomo.@nameserver[4].type='fallback'
mihomo.@nameserver[4].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='geosite:cn,private'
mihomo.@nameserver_policy[0].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='geosite:geolocation-!cn'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.editor=editor
mihomo.log=log

### 配置文件

```yaml
config status 'status'

config config 'config'
	option enabled '1'
	option scheduled_restart '1'
	option cron_expression '0 3 * * 3'
	option profile 'subscription:subscription'
	option mixin '1'
	option test_profile '1'
	option fast_reload '0'

config proxy 'proxy'
	option transparent_proxy '1'
	option tcp_transparent_proxy_mode 'redirect'
	option udp_transparent_proxy_mode 'tun'
	option ipv4_dns_hijack '1'
	option ipv6_dns_hijack '1'
	option ipv4_proxy '1'
	option ipv6_proxy '1'
	option router_proxy '1'
	option lan_proxy '1'
	option access_control_mode 'all'
	option bypass_china_mainland_ip '0'
	option acl_tcp_dport '0-65535'
	option acl_udp_dport '0-65535'

config subscription 'subscription'
	option name 'xxx.xxx.com'
	option url 'https://xxx.xxx.com/meta.yml'
	option user_agent 'clash.meta'

config mixin 'mixin'
	option log_level 'warning'
	option mode 'rule'
	option match_process 'off'
	option ipv6 '1'
	option tcp_keep_alive_idle '600'
	option tcp_keep_alive_interval '15'
	option ui_name 'metacubexd'
	option ui_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
	option api_port '9999'
	option selection_cache '1'
	option allow_lan '1'
	option http_port '8080'
	option socks_port '1080'
	option mixed_port '7890'
	option redir_port '7891'
	option tproxy_port '7892'
	option authentication '1'
	option tun_stack 'mixed'
	option tun_mtu '9000'
	option tun_gso '1'
	option tun_gso_max_size '65536'
	option tun_endpoint_independent_nat '0'
	option dns_port '1053'
	option dns_mode 'fake-ip'
	option fake_ip_range '198.18.0.1/16'
	option fake_ip_filter '0'
	list fake_ip_filters '+.lan'
	list fake_ip_filters '+.local'
	option fake_ip_cache '1'
	option dns_respect_rules '0'
	option dns_doh_prefer_http3 '0'
	option dns_ipv6 '1'
	option dns_system_hosts '0'
	option dns_hosts '1'
	option hosts '0'
	option dns_nameserver '0'
	option dns_nameserver_policy '0'
	option geoip_format 'dat'
	option geodata_loader 'memconservative'
	option geosite_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
	option geoip_mmdb_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
	option geoip_dat_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
	option geoip_asn_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
	option geox_auto_update '1'
	option geox_update_interval '72'
	option api_secret 'xueyuhappy'

config authentication
	option enabled '1'
	option username 'mihomo'
	option password '138449'

config host
	option enabled '0'
	option domain_name 'localhost'
	list ip '127.0.0.1'
	list ip '::1'

config nameserver
	option enabled '1'
	option type 'default-nameserver'
	list nameserver '223.5.5.5'
	list nameserver '119.29.29.29'

config nameserver
	option enabled '1'
	option type 'proxy-server-nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver
	option enabled '1'
	option type 'direct-nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver
	option enabled '1'
	option type 'nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver
	option enabled '0'
	option type 'fallback'
	list nameserver 'https://dns.cloudflare.com/dns-query'
	list nameserver 'https://dns.google/dns-query'

config nameserver_policy
	option enabled '1'
	option matcher 'geosite:cn,private'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver_policy
	option enabled '1'
	option matcher 'geosite:geolocation-!cn'
	list nameserver 'https://dns.cloudflare.com/dns-query'
	list nameserver 'https://dns.google/dns-query'

config editor 'editor'

config log 'log'
```

### 插件日志

[2024-10-21 14:26:52] App is enabled.
[2024-10-21 14:26:52] Starting...
[2024-10-21 14:26:54] Use Subscription: up.liuweinan.com
[2024-10-21 14:26:54] Mixin is enabled, mixin all config.
[2024-10-21 14:27:09] Profile testing...
[2024-10-21 14:27:09] Profile test passed!
[2024-10-21 14:27:09] Start Core
[2024-10-21 14:27:09] Transparent Proxy is enabled.
[2024-10-21 14:27:09] Transparent Proxy: Start.
[2024-10-21 14:27:09] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-10-21 14:27:09] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-10-21 14:27:09] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-10-21 14:27:09] Transparent Proxy: IPv6 Proxy is enabled, set proxy for IPv6 traffic.
[2024-10-21 14:27:09] Transparent Proxy: Destination TCP Port to Proxy: 0-65535.
[2024-10-21 14:27:09] Transparent Proxy: Destination UDP Port to Proxy: 0-65535.
[2024-10-21 14:27:09] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-10-21 14:27:10] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-10-21 14:27:10] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-10-21 14:27:10] Add crontab for scheduled restart.
[2024-10-21 14:27:10] Start Successful!

### 核心日志

time="2024-10-21T14:27:09.524219565+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-21T14:27:09.571200653+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-21T14:27:09.571306643+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-21T14:27:09.624938563+08:00" level=info msg="Load GeoIP rule: cn"
time="2024-10-21T14:27:09.682543609+08:00" level=info msg="Finished initial GeoIP rule cn => .... ............, records: 7464"
time="2024-10-21T14:27:09.683487098+08:00" level=info msg="Finished initial GeoIP rule cn => dns.fallback-filter.geoip, records: 7464"
time="2024-10-21T14:27:09.6846909+08:00" level=info msg="Initial configuration complete, total time: 160ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-10-21T14:27:10.370806858+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-21T14:27:10.412910811+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-21T14:27:10.4130218+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-21T14:27:10.466287158+08:00" level=info msg="Load GeoIP rule: cn"
time="2024-10-21T14:27:10.765748059+08:00" level=info msg="Finished initial GeoIP rule cn => .... ............, records: 7464"
time="2024-10-21T14:27:10.766683007+08:00" level=info msg="Finished initial GeoIP rule cn => dns.fallback-filter.geoip, records: 7464"
time="2024-10-21T14:27:10.767842174+08:00" level=info msg="Initial configuration complete, total time: 396ms"

### 附加信息

可以使用这个节点信息测试：vless://d342d11e-d424-4583-b36e-524ab1f0afa4@51.79.254.182:443?encryption=none&security=tls&sni=cfworkers.liuweinan85.workers.dev&fp=randomized&type=ws&host=cfworkers.liuweinan85.workers.dev&path=%2F%3Fed%3D2048#cfworkers.liuweinan85.workers.dev

**Comment by 1345695** [comment]
workers.dev本身就是被墙的，能访问就见鬼了

**Comment by Java2Boy** [comment]
同样问题，shellcrash 可以使用，同样在openclash中导入yaml订阅文件无问题，在本插件无论是订阅还是yaml文件都无法使用，面板里直接空白
