### ISSUE TITLE
[Feature Request]绕过中国大陆 IP增加黑名单域名和ip以访问外网版bing

### ISSUE THREAD

**Issue by haohaoget** [morytyann/OpenWrt-mihomo#259]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

开启绕过中国大陆 IP功能后访问bing.com会被重定向到国内版，关闭后可正常分流。
希望增加一个绕过中国大陆 IP的黑名单域名和ip功能，能将bing.com排除到绕过名单外

**Comment by wally94** [comment]
配置文件里给必应或者微软的域名设置nameserver-policy为外网的dns可以解决
比如：
  nameserver-policy:
    "rule-set:microsoft_domain,geolocation-!cn":
      - "https://dns.google/dns-query"

**Comment by wally94** [comment]
只是我自己测试的结果哈，因为我也遇到这个情况，出现的原因可能是第一次DNS查询的时候，返回的是大陆的IP，然后又被绕过，不经过核心，所以导致的。然后根据这个猜想，给微软系的域名设置了一个单独的DNS，nameserver-policy选项优先于其他任何dns设置，所以用外网的DNS查询的情况下，返回的就是外网的IP了，这样就不会绕过了。具体对不对还得你自己测试一下。

**Comment by haohaoget** [comment]
> 可以用 @wally94 的方法。
> 
> 你应该用的redir-host模式吧，可以切换到fake-ip，并在fake-ip-filter里添加`GEOSITE:cn`，这样对于大陆域名还是返回真实IP，此时绕过大陆也是可以生效。

确实是dns的问题已解决感谢
