### ISSUE TITLE
能否增加绕过国内流量不经过mihomo，以增强代理性能。

### ISSUE THREAD

**Issue by qaz69** [morytyann/OpenWrt-mihomo#28]
现在的所有的流量是经过mihomo的，不知能能否把国内流量绕过mihomo，因为某些BT下载的时候，连接数大，经过mihomo下载速度会下降。还有上次测试了一下，手动更换mihomo内核，可以运行，但是无法代理。

**Comment by morytyann** [comment]
可以添加此功能，但即使可以绕过国内流量，如果BT下载的对端是国外的话还是会经过核心，建议的做法是单独用一台机器做下载机，然后在访问控制中排除它。

**Comment by morytyann** [comment]
关于更换内核不能代理的问题，更换内核不是预期的行为，请自行排查解决
