### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lencil** [morytyann/OpenWrt-mihomo#285]
### 自查

- [x] OpenWrt 版本在 23.05 及以上
- [X] Linux Kernel 版本在 5.10 及以上
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到相关问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由此仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

OpenWrt

### BUG 描述

在mihomo luci面板中“基础配置” -> "启用“复选框，选中的情况下，重启路由器。
mihomo服务有时没有启动成功，查看日志是mihomo有时在第一次启动时，如果没有正确拉取clash配置文件，便会一直保持“未运行”状态。

### 预期行为

如果 在mihomo luci面板中“基础配置” -> "启用“复选框，选中的情况下:
如果mihomo service启动失败，则应该定时尝试启动。而非僵在那里。

### 复现步骤

在mihomo luci面板中“基础配置” -> "启用“复选框，选中的情况下，让wan口断掉互联网连接，重启路由器。此时由于mikomo拉取配置失败，服务就不会启动，再次将wan口启动互联网，mikomo会一直保持“未运行”，而非定时尝试启动。

### 调试信息

无

### 插件日志

无

### 核心日志

无

**Comment by lencil** [comment]
补充一点疑问，我理解的“定时重起”选项的策略是不管service是否正常，都会按照cron设置的时间定时重起吧？
我建议如果service没有启动成功时，应该自动更若干毫秒尝试重启，或给予ui自行配置。

**Comment by lencil** [comment]
是否可以考虑procd_set_param respawn设置一下失败重启策略？

**Comment by asdsohu** [comment]
我也一直遇到这个问题看到没人反馈这个问题一直以为是我自己系统问题，升级多个新版本还一样无法自动启动，我的openwrt也换了新版本重启op，mihomo还是无法自动启动

**Comment by asdsohu** [comment]
最新的1.93设置了启动延迟10，重启还是核心状态未运行

**Comment by lencil** [comment]
clash config file cache, works fine.
