### ISSUE TITLE
[Feature Request] 订阅失败后回退到使用上次的缓存配置文件启动

### ISSUE THREAD

**Issue by yegetables** [morytyann/OpenWrt-mihomo#299]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

因为订阅链接由ddns域名生成,重启时因为优先顺序原因,在一段时间内域名无法访问.
但是重启openwrt-mihomo时会拉取订阅,如果链接失效则无法正常启动
希望可以缓存上次正常的启动配置作为回退策略,而不是直接失败

**Comment by yegetables** [comment]
1.9.1-1是不是没有实现

**Comment by psqtdhx** [comment]
> 是的，更新下吧。

哦，优先 里面的 远程/本地 是干这个用的啊
