### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mordekaiser43** [morytyann/OpenWrt-mihomo#310]
### 自查

- [X] OpenWrt 版本在 23.05 及以上
- [X] Linux Kernel 版本在 5.10 及以上
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到相关问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由此仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### BUG 描述

先致谢。
问题描述：
从软件仓库直接更新后，插件设置页面版本号和核心号不再显示。当前版本1.13.1，此问题在升级1.13.0时也出现过。其他人也有出现过此问题。卸载安装后重新从feed安装或者直接curl安装版本显示正常无问题。
不是必须需求，作者大大如有时间辛苦看看，认为没必要辛苦closed。（ps第一次提issue,格式不正确或提问方式有误希望见谅）。
immortalwrt 版本：ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.314.43925-4431ab0
内核版本：5.15.162
架构：x86
![屏幕截图 2024-11-25 191855](https://github.com/user-attachments/assets/7924301c-6142-4c0d-be86-f5e322fbd72e)

### 预期行为

按照之前预期，升级后应该可以正常显示内核和插件版本号

### 复现步骤

复现未能成功。卸载最新版本1.13.1后手动上传1.11.0，从openwrt系统软件包中点击更新后能正常显示插件版本号和内核版本号alpha-eb985b0。

### 调试信息

无

### 插件日志

无

### 核心日志

无

### 附加信息

无

**Comment by Mordekaiser43** [comment]
> mihomo是不是没有更新啊，更新它就好了，理论上三个是配套的，mihomo提供二进制和脚本，luci-app只提供界面用于配置和查看，i18n提供翻译，所以需要同时更新到最新>>如果使用feed而不无法更新，那是因为feed重构了（#300），需要重新添加下（直接执行即可，自行删掉旧的），添加建议建议先卸载完成后再重新安装。
----------------------------------------------------------------------------------------------------------------
感谢作者大回复，我在官方版本openwrt上排查了一下。
curl重新添加源，opkg源内显示地址：src/gz mihomo https://morytyann.github.io/OpenWrt-mihomo/openwrt-23.05/x86_64/mihomo
更新软件包列表，在可用中搜索mihomo显示内核、插件、中文包可更新如图所示
![图像]（https://github.com/user-attachments/assets/7e6906f4-100e-4f87-aa69-08915e0f6a2f）
在更新中搜索mihomo只显示插件和中文包更新，不显示内核。
![1732536903046]（https://github.com/user-attachments/assets/ec5f5ab7-b73c-40cc-816e-65e4e828c3ca）
这个现象在immortalwrt上也同样出现，第一次出现时间节点应该是之前11版本更新时源地址一次变更的时候。
从软件包直接更新插件,更新前显示版本1.11.1 内核alpha-3e966e8
![image](https://github.com/user-attachments/assets/9f5dde2d-3c72-47f4-a333-ef2be8fa363c)
从可用点击mihomo内核更新，提示如图
![image](https://github.com/user-attachments/assets/cc4a1faf-8f91-4b54-93f9-852b3c5b95e8)
然后来到更新里点击插件后的更新，更新成功没有报错，在可用中重新搜索，显示内核版本号已经是最新版本号但仍显示升级（immortalwrt也是有这个现象）
![image](https://github.com/user-attachments/assets/6f0b4bce-b219-4d71-983a-4a5be793bbf3)
此时插件页面插件版本号和内核版本号为空白。
![image](https://github.com/user-attachments/assets/feaa4219-ca4a-4854-8cfe-55d1303ac438)

**Comment by Mordekaiser43** [comment]
> 这个算是opkg的bug。
> 
> 我也遇到过无法更新的情况，想要解决，需要手动安装之前安装的的版本（通过 `opkg status 包名`获取，你会看到两个，但应该只有一个才对），然后卸载，再从feed里安装就可以了。
> 
> 如果觉得麻烦，可以用安装脚本来安装，不然就重刷固件。
> 
> 根本原因就是我重构了构建相关的脚本，从使用snapshot的sdk改为使用对应的sdk来构建，导致版本号格式变化了（snapshot为了兼容apk，修改了版本号格式），然后opkg的bug又导致卸载的包的信息遗留在本地（我没有找到在哪里，至少不是更新时提示的那个list，大概是有一个数据库），你更新提示成功实际上是错误的，他错误的采用了已经卸载的包的信息，实际上并没有安装成功。

感谢作者大大指点，我之前觉得应该是版本号问题导致的，但是我的知识储备不够不敢确认。再次谢谢作者大大指点学习了可以通过openg status包名来获取解决。能否追问一个问题，在1.30版本中增加了路由用户和用户组的绕过，1.31版本中一些用户和组（ftp 、nobody 、ntp、dnsmasq、logd、ubus）默认勾选了绕过，以我的知识储备这些用户和组是可以不用通过代理的，所以可以勾选绕过，这里默认即可不用再取消勾选。不知道是否正确？

**Comment by Mordekaiser43** [comment]
> 默认就行，这个主要是用来绕过dnsmasq的，这样Mihomo的DNS可以指向127，而不会回环。
> 
> 再就是可以绕过aria2等下载软件，对于把路由器当轻nas的有用。

好的，再次致谢，占用您的时间了，感谢您的回复又学习了知识。还发现竟然贴心的给老版本的包也增加了apk，真的很棒。最后再次致谢，我把这个issue close了。

**Comment by qljsyph** [comment]
> 后续

感谢大佬还记得呢，我记下了上次我卸载了然后重新装，最新的两个版本都顺利直接从feed升级了。
