### ISSUE TITLE
[Feature Request] 谷歌商店下载与绕过中国大陆共存

### ISSUE THREAD

**Issue by f0rfuc** [morytyann/OpenWrt-mihomo#311]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相同/类似的功能请求

### 功能描述

https://github.com/vernesong/OpenClash/discussions/3131
也可能不是这个问题，但是我只要打开绕过中国大陆，下载就是一直转圈，且连接很少
![image](https://github.com/user-attachments/assets/8930faca-5923-4a78-bd60-050d3d7e84cc)
关闭后（中途不取消下载）
![image](https://github.com/user-attachments/assets/ca6b4286-aa36-4ce4-bc47-989b1a7d0602)
等待一段时间后（下载的是多邻国47M，奇怪的是走的googlevideo.com的规则）
![image](https://github.com/user-attachments/assets/171fb30d-209a-4453-ae23-404f6a6778f1)
```个人猜测因为绕过大陆所以不会走mihomo```
也出现xn--ngstr-lra8j.com了，但是不走直连也没事,只要关闭绕过大陆就能下载
![image](https://github.com/user-attachments/assets/bf002eba-6d5e-4edc-bc76-17965bc5eb63)

### 如何实现

希望添加绕过大陆黑名单
![image](https://github.com/user-attachments/assets/15b99414-3cc0-42b4-bad8-a17781a1f518)
网上是这样说可以解决

**Comment by f0rfuc** [comment]
openclash 加了这个也没用，看来不是黑名单的问题，我还是就不用绕过大陆吧

**Comment by kaixinoli** [comment]
![image](https://github.com/user-attachments/assets/3102f90b-14ae-462f-b631-4c3e9d68c4f9)
在这里加上最后两个就可以了

**Comment by f0rfuc** [comment]
还是没用，我又发现一个新的问题就是raw.githubusercontent.com 无法访问，偶尔就来个解析不到，这是被dns阻断了吗

**Comment by f0rfuc** [comment]
解决了开tun就好了，但是raw.githubusercontent.com 无法访问还是没有解决

**Comment by f0rfuc** [comment]
> Play Store无法下载的问题，即使加入绕过大陆黑名单也不一定能解决。
> 
> 可以参考这篇[文章](https://www.0z.gs/android/2077.html)配置一下规则试试。

我加上了没用，应该绕过规则给我绕丢了

**Comment by f0rfuc** [comment]
> openclash 加了这个也没用，看来不是黑名单的问题，我还是就不用绕过大陆吧，即使开了Gobal全局代理也不能下载。

openclash加了这个规则有用，当时切换到openclash没重启路由器，怪不得没测出来...
![image](https://github.com/user-attachments/assets/b4c03595-e6b0-45f6-ab64-e056bd9d985b)

**Comment by z1gc** [comment]
这个是因为 geosite:cn 实际上包含了所有的 +.cn 域名，并且你这里配置的优先级比 services 更高，把 service 放到 geosite:cn 之前或许就能解决了。

**Comment by NaiHeKK** [comment]
> ![image](https://github.com/user-attachments/assets/3102f90b-14ae-462f-b631-4c3e9d68c4f9) 在这里加上最后两个就可以了

感谢，按照这个配置加上列表并且设为黑名单模式就行了

**Comment by edward4hgl** [comment]
> > ![image](https://github.com/user-attachments/assets/3102f90b-14ae-462f-b631-4c3e9d68c4f9) 在这里加上最后两个就可以了
> 
> 感谢，按照这个配置加上列表并且设为黑名单模式就行了

我试过还是不行，请问您是按照截图的顺序，还是把geosite:cn放最后了？然后代理配置--绕过--绕过中国大陆IP还打开吗？

**Comment by NaiHeKK** [comment]
> > > ![image](https://github.com/user-attachments/assets/3102f90b-14ae-462f-b631-4c3e9d68c4f9) 在这里加上最后两个就可以了
> > 
> > 
> > 感谢，按照这个配置加上列表并且设为黑名单模式就行了
> 
> 我试过还是不行，请问您是按照截图的顺序，还是把geosite:cn放最后了？然后代理配置--绕过--绕过中国大陆IP还打开吗？

我现在是把这个加到了配置文件里
fake-ip-filter-mode: blacklist
然后上面两个加到fake-ip-filter最后，开启绕过中国ip，代理模式均为tun
