### ISSUE TITLE
[BUG]访问控制黑名单模式不生效。

### ISSUE THREAD

**Issue by sjkhsl** [morytyann/OpenWrt-mihomo#316]
### 自查

- [X] OpenWrt 版本在 23.05 及以上
- [X] Linux Kernel 版本在 5.10 及以上
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到相关问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由此仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### BUG 描述

局域网有pt，已经添加访问控制黑名单，ip和mac都尝试过。不生效。

### 预期行为

希望访问控制模式正常使用。

### 复现步骤

开启访问控制黑名单模式。

### 调试信息

没试过，运行没啥问题。

### 插件日志

[2024-12-01 02:58:13] App is enabled.
[2024-12-01 02:58:13] Starting...
[2024-12-01 02:58:13] Use Subscription: sub-store.
[2024-12-01 02:58:13] Update Subscription: sub-store.
[2024-12-01 02:58:14] Subscription update succeed.
[2024-12-01 02:58:14] Mixin is disabled, only mixin neccesary config.
[2024-12-01 02:58:14] Profile testing...
[2024-12-01 02:58:15] Profile test passed!
[2024-12-01 02:58:15] Start Core
[2024-12-01 02:58:15] Transparent Proxy is enabled.
[2024-12-01 02:58:15] Transparent Proxy: Start.
[2024-12-01 02:58:15] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-12-01 02:58:15] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-12-01 02:58:15] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-12-01 02:58:15] Transparent Proxy: IPv6 Proxy is enabled, set proxy for IPv6 traffic.
[2024-12-01 02:58:15] Transparent Proxy: Destination TCP Port to Proxy: 21 22 80 110 143 194 443 465 853 993 995 8080 8443.
[2024-12-01 02:58:15] Transparent Proxy: Destination UDP Port to Proxy: 123 443 8443.
[2024-12-01 02:58:15] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-12-01 02:58:15] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-12-01 02:58:15] Transparent Proxy: Access Control is using block mode, set proxy for client which is not in acl.
[2024-12-01 02:58:15] Start Successful!

### 核心日志

time="2024-12-01T02:58:14.334288142+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-01T02:58:14.335311484+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-01T02:58:14.33532782+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-01T02:58:14.335655596+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-01T02:58:15.057790042+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97839"
time="2024-12-01T02:58:15.058094904+08:00" level=info msg="Initial configuration complete, total time: 723ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-12-01T02:58:15.505687064+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-01T02:58:15.506757769+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-01T02:58:15.506793975+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-01T02:58:15.507138982+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-01T02:58:16.213948848+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97839"
time="2024-12-01T02:58:16.214325133+08:00" level=info msg="Initial configuration complete, total time: 708ms"
time="2024-12-01T03:00:34.006161582+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: connect: connection timed out"
time="2024-12-01T03:00:37.004927414+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) [2408:822a:]:40474 --> [2408:80f1:21:c124::1f]:80 error: dns resolve failed: ip version error"
time="2024-12-01T03:02:52.246149286+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: connect: connection timed out"
time="2024-12-01T03:05:36.086191587+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: connect: connection timed out"
time="2024-12-01T03:07:06.218484299+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: operation was canceled"
time="2024-12-01T03:07:56.957529656+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: operation was canceled"
time="2024-12-01T03:08:32.416604241+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) [2408:822a]:44672 --> [2402:4e00:1411:601:0:9984:c4d1:fcf9]:80 error: dns resolve failed: ip version error"
time="2024-12-01T03:08:32.41667159+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) [2408:]:49558 --> [2402:4e00:1408:9200:0:9b36:8965:d4a]:80 error: dns resolve failed: ip version error"
time="2024-12-01T03:10:48.406155996+08:00" level=warning msg="[TCP] dial 🌏 中国直连 (match RuleSet/cn_ip) mihomo --> 119.29.29.29:443 error: dial tcp 119.29.29.29:443: connect: connection timed out"

**Comment by sjkhsl** [comment]
> 测试不能复现，你的意思是不是添加以后，面板里还有连接？黑白名单变动后并不会断开连接，你可以在面板手动断开它们，或者重启服务。

额，可能描述有问题，我的意思是加入黑名单的地址还是会被代理。

**Comment by refined-fish** [comment]
> > 测试不能复现，你的意思是不是添加以后，面板里还有连接？黑白名单变动后并不会断开连接，你可以在面板手动断开它们，或者重启服务。
> 
> 额，可能描述有问题，我的意思是加入黑名单的地址还是会被代理。

你想要的或许是绕过功能，请将你的IP添加到保留地址再试试

**Comment by sjkhsl** [comment]
> 啊？你填写的是你跑PT机器的IP/MAC，还是目标IP/MAC？这里是填写源IP/MAC的……

我填写的是pt机器的ip和mac。

**Comment by refined-fish** [comment]
> > 啊？你填写的是你跑PT机器的IP/MAC，还是目标IP/MAC？这里是填写源IP/MAC的……
> 
> 我填写的是pt机器的ip和mac。

截图看看呢，大概是啥样的？

**Comment by sjkhsl** [comment]
> 大概是DNS缓存？
> 
> 你清理下PT机器的DNS缓存试试？既然流量绕过了，DNS请求也应该绕过了，毕竟是一样的逻辑。
> 
> 还有一个可能是，你的DNS没有指向此路由器，你的网络拓扑是什么样的？

我试试清空dns缓存，我网络拓扑就是软路由拨号做主路由，运行mihomo。

**Comment by funfunfeifei** [comment]
> > 大概是DNS缓存？
> > 你清理下PT机器的DNS缓存试试？既然流量绕过了，DNS请求也应该绕过了，毕竟是一样的逻辑。
> > 还有一个可能是，你的DNS没有指向此路由器，你的网络拓扑是什么样的？
> 
> 我试试清空dns缓存，我网络拓扑就是软路由拨号做主路由，运行mihomo。

解决了吗，我也是一样，skipping tracker announce unreachable报这个错
