### ISSUE TITLE
开启插件后，NAT类型成为UdpBlocked？

### ISSUE THREAD

**Issue by JohnsonRan** [morytyann/OpenWrt-mihomo#34]
开启前是Fullcone，开启后就变成了udpblocked，已确定测试地址是直连  
![屏幕截图 2024-07-17 234646](https://github.com/user-attachments/assets/b5b1d3cb-e84b-4352-b4b2-303ac45b033b)
没测试过其他插件，可能是我自己问题？

**Comment by morytyann** [comment]
节点要支持UDP（VMESS和VLESS除外），还要使用Redir-Host模式或者在Fake-IP过滤列表添加STUN的域名

**Comment by morytyann** [comment]
![image](https://github.com/user-attachments/assets/4e713d6c-4b25-48f9-94fc-d5e9ba53edb4)
我使用的是官方OpenWrt，没有打FullCone的补丁，这个结果和未开启插件时是相同的

**Comment by JohnsonRan** [comment]
> 节点要支持UDP（VMESS和VLESS不行），还要使用Redir-Host模式或者在Fake-IP过滤列表添加STUN的域名

走直连也需要节点支持udp吗

**Comment by morytyann** [comment]
直连不需要，游戏联机的情况下需要

**Comment by JohnsonRan** [comment]
我图里确实是工具用的stun.miwifi.com走了直连，但是NAT类型不是fullcone
用的redir-host模式

**Comment by morytyann** [comment]
试试让syncthing走代理，再测一下它的NAT类型

**Comment by JohnsonRan** [comment]
啊，节点不支持udp会导致就算走直连也会udpblocked吗

**Comment by morytyann** [comment]
不是这个意思，只是想看看这样的结果，排查一下是哪里的原因

> 啊，节点不支持udp会导致就算走直连也会udpblocked吗

**Comment by JohnsonRan** [comment]
看了下mihomo日志，好像知道原因了...但不知道为什么
[warning]
[UDP] dial DIRECT(match GeolP/cn)我的公网IP:44891->我的公网IP:58366 error: reject loopback connection to: 我的公网IP:58366

**Comment by morytyann** [comment]
`nft list set mihomo private_ip`，运行一下这个命令，看看里面有没有你的公网IP，没有的话，问题就出在IP变了但插件没有重新添加进去

**Comment by JohnsonRan** [comment]
没有，刚刚重新启用插件后有了，并且udp也是fullcone了...

**Comment by JohnsonRan** [comment]
我怀疑是因为每次重启mihomo比网络先启动，导致公网IP没被添加到表内
因为每次重启都会出现上面的warning

**Comment by morytyann** [comment]
关于启用后NAT类型变成PortRestrictedCone，只要流量经过了插件就会这样，可以参考OpenClash的[ISSUE](https://github.com/vernesong/OpenClash/issues/2288)
关于公网IP入站没有跳过的问题，我这边测试过是正常的，无论是重启系统还是重启接口，你也是PPPoE拨号吗？

**Comment by JohnsonRan** [comment]
知道了，感谢~~帮我Google~~
应该是因为我在`/etc/sysupgrade.conf`添加了`/etc/mihomo`想让更新固件后不用重新下载一些东西，结果导致文件夹下所有内容很久都没更新过的原因（

**Comment by morytyann** [comment]
嗯，重装一下插件，再试试公网IP能否正常跳过，正常的话就关掉ISSUE了🤗

**Comment by JohnsonRan** [comment]
正常了🤣

**Comment by JohnsonRan** [comment]
找到根本原因了，是因为我添加了一个SFP接口用来访问我的猫棒。重启之后插件似乎把SFP接口当成出口导致上面问题
是否有办法加一个选择接口的地方呢
虽然[mihomo](https://wiki.metacubex.one/en/config/general/#outbound-interface)可以设置，但是会导致用同配置的其他设备出现问题吧（？

**Comment by morytyann** [comment]
请你新开一个ISSUE吧，关于Wan接口获取错误的问题的。
