### ISSUE TITLE
[Feature Request] 重构 LuCI 界面

### ISSUE THREAD

**Issue by morytyann** [morytyann/OpenWrt-mihomo#347]
### 确认

- [X] 我已经查看过Wiki，没有找到我想要的功能
- [X] 我已经搜索过Issue，没有找到相关的功能请求
- [X] 我提交的是一个功能请求，而非其它的内容
- [X] 我明白如果我不遵循模板填写，Issue将会被关闭
- [ ] 我是为了提交Issue才选择了上述选框，我不知道我在做什么

### 功能描述

目前界面将所有配置项都放在了同一个页面中，优点是只需上下滚动即可配置完成，但这也是个缺点，过长的页面并不友好。

出于想对比一下分开和合在一起哪个更好一些的想法，我在v1.14.0分支做了如下修改：

1. 配置更名为插件配置，仅保留之前的状态、插件配置和核心环境变量配置
2. 新增配置文件标签，包含之前的上传配置文件和订阅配置
3. 新增混入配置标签，包含混入的开关和之前的混入配置（更名为混入选项）
4. 新增代理配置标签，包含之前的代理配置
5. 日志与编辑器保持不变

我个人用起来有点不顺手，毕竟使用习惯已经养成了，但是界面的观感好了，页面不再显得拥挤，基本每一个标签在2K下最大化窗口中都可以一个屏幕就看完所有选项。

### 如何实现

重构 LuCI 界面

### 附加信息

发布这个Issue的目的是想知道大家的想法，如果你觉得这是个好的改动的话请点👍，反对的话请点👎。

**Comment by 77160860** [comment]
大佬  HY2节点支持是不是不完善啊  每次启动HY2就巨卡   上不了网了
reality正常

**Comment by 77160860** [comment]
> OpenWrt的版本和Linux内核版本？

![op](https://github.com/user-attachments/assets/203cb210-5dfc-476b-9f8d-3be22fd5163b)
开的tun+tun模式

**Comment by 77160860** [comment]
这是开启hy2后的内核日志  没看到xray内核启动
time="2024-12-15T20:39:41.565169218+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-15T20:39:41.567793832+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-15T20:39:41.567901949+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-15T20:39:41.569047809+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-15T20:39:46.825147488+08:00" level=info msg="Finished initial GeoSite rule CN => DIRECT, records: 97626"
time="2024-12-15T20:39:46.827669193+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-12-15T20:39:48.435824189+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => 手动选择, records: 31011"
time="2024-12-15T20:39:48.436505185+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 97626"
time="2024-12-15T20:39:48.436660279+08:00" level=info msg="Load GeoSite rule: private"
time="2024-12-15T20:39:50.028678585+08:00" level=info msg="Finished initial GeoSite rule private => dns.nameserver-policy, records: 131"
time="2024-12-15T20:39:50.029327448+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97626"
time="2024-12-15T20:39:50.029542538+08:00" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2024-12-15T20:39:50.030316757+08:00" level=info msg="Initial configuration complete, total time: 8464ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-12-15T20:39:52.820441173+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-15T20:39:52.822784402+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-15T20:39:52.822876636+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-15T20:39:52.8235468+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-15T20:39:57.789988851+08:00" level=info msg="Finished initial GeoSite rule CN => DIRECT, records: 97626"
time="2024-12-15T20:39:57.790908468+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-12-15T20:39:59.56191053+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => 手动选择, records: 31011"
time="2024-12-15T20:39:59.562593759+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 97626"
time="2024-12-15T20:39:59.562767392+08:00" level=info msg="Load GeoSite rule: private"
time="2024-12-15T20:40:00.285963927+08:00" level=info msg="Finished initial GeoSite rule private => dns.nameserver-policy, records: 131"
time="2024-12-15T20:40:00.28666705+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97626"
time="2024-12-15T20:40:00.286928905+08:00" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2024-12-15T20:40:00.287895498+08:00" level=info msg="Initial configuration complete, total time: 7467ms"

**Comment by 77160860** [comment]
这是启动reality后的启动日志  这个正常
time="2024-12-15T20:44:45.07743477+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-15T20:44:45.079845436+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-15T20:44:45.079930847+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-15T20:44:45.080897081+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-15T20:44:52.296718859+08:00" level=info msg="Finished initial GeoSite rule CN => DIRECT, records: 97626"
time="2024-12-15T20:44:52.297605048+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-12-15T20:44:54.508511697+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => 手动选择, records: 31011"
time="2024-12-15T20:44:54.509087178+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 97626"
time="2024-12-15T20:44:54.509243104+08:00" level=info msg="Load GeoSite rule: private"
time="2024-12-15T20:44:55.133533921+08:00" level=info msg="Finished initial GeoSite rule private => dns.nameserver-policy, records: 131"
time="2024-12-15T20:44:55.134060447+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97626"
time="2024-12-15T20:44:55.134221947+08:00" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2024-12-15T20:44:55.134905129+08:00" level=info msg="Initial configuration complete, total time: 10057ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-12-15T20:44:57.904931832+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-15T20:44:57.907349374+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-12-15T20:44:57.90743692+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-15T20:44:57.908132705+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-12-15T20:45:03.50047112+08:00" level=info msg="Finished initial GeoSite rule CN => DIRECT, records: 97626"
time="2024-12-15T20:45:03.501340071+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-12-15T20:45:05.883854625+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => 手动选择, records: 31011"
time="2024-12-15T20:45:05.88442943+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 97626"
time="2024-12-15T20:45:05.884584055+08:00" level=info msg="Load GeoSite rule: private"
time="2024-12-15T20:45:06.467662808+08:00" level=info msg="Finished initial GeoSite rule private => dns.nameserver-policy, records: 131"
time="2024-12-15T20:45:06.4681772+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 97626"
time="2024-12-15T20:45:06.468348282+08:00" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2024-12-15T20:45:06.468911629+08:00" level=info msg="Initial configuration complete, total time: 8563ms"
time="2024-12-15T20:45:06.561145989+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-12-15T20:45:06.56150961+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-12-15T20:45:06.561792455+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-12-15T20:45:06.562034209+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"

**Comment by Sauhun** [comment]
个人非常喜欢 选项卡 方式的调整！虽然用起来没有什么太大区别，一个是通过点击选项卡，一个是滚动页面。

**Comment by minisind** [comment]
看起来显得更加整齐有序。喜欢这个界面。

**Comment by Mipa233** [comment]
> 有一个可能影响体验的区别，上面的标签切换是要刷新页面的，因此如果想一次性配置分布在不同标签的配置项时，需要点击保存，完成配置后再点击保存并应用。
> 
> > 个人非常喜欢 选项卡 方式的调整！虽然用起来没有什么太大区别，一个是通过点击选项卡，一个是滚动页面。

这样的话那我觉得不太行..还是喜欢一次就配置完成。

**Comment by refined-fish** [comment]
> 有一个可能影响体验的区别，上面的标签切换是要刷新页面的，因此如果想一次性配置分布在不同标签的配置项时，需要点击保存，完成配置后再点击保存并应用。

openclash中一个大标签页下的子标签页切换不会丢失未保存的配置，那个子页面是咋实现的

**Comment by refined-fish** [comment]
> 上面那一行切换会丢，下面的不会，一样的。当前正式版MTP的不也是吗，如果你配置里修改了没保存，切换到编辑器或者日志就丢了…… 

我是这意思，但是我脑子抽了，忘了mtp也是已经用了这个功能了没法套娃😂

**Comment by 77160860** [comment]
能否加入重置功能？
