### ISSUE TITLE
请求添加只代理常用端口功能

### ISSUE THREAD

**Issue by H2295** [morytyann/OpenWrt-mihomo#35]
udp dport != { 22, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 5222, 8080, 8443 } counter packets 0 bytes 0 return
tcp dport != { 22, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 5222, 8080, 8443 } counter packets 0 bytes 0 return
能不能在防火墙规则那里添加类似上面的规则

**Comment by morytyann** [comment]
添加了要代理的TCP/UDP目标端口选项，默认代理全部端口，可选择常用端口或自行设置，格式为空格分割，例如`80 443 8080 8443`。此选项和绕过中国大陆IP一样，在Fake-IP下只有纯IP连接能够绕过。

**Comment by H2295** [comment]
> 添加了要代理的TCP/UDP目标端口选项，默认代理全部端口，可选择常用端口或自行设置，格式为空格分割，例如`80 443 8080 8443`。此选项和绕过中国大陆IP一样，在Fake-IP下只有纯IP连接能够绕过。

是要自己编辑hijack.nft，自己添加端口对吗？
ps：你们的MetaCubeXD 面板首页能显示内存占用吗？

**Comment by morytyann** [comment]
之前没不关注内存占用，所以没注意，刚看了下，内存使用情况是0B，可能是权限问题，等着处理下

**Comment by morytyann** [comment]
内存使用情况获取不到的问题修复了
