### ISSUE TITLE
[BUG]无法打开面板

### ISSUE THREAD

**Issue by xuhuanzy** [morytyann/OpenWrt-mihomo#358]
### 自查

- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我已经搜索过Issue，没有找到相关问题
- [X] 我使用的是通过仓库Release或Feed安装的最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供的信息里不包含公网IPv4地址、公网IPv6地址、MAC、代理节点等敏感信息
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息
- [X] 我明白如果我不遵循模板填写，Issue将会被关闭
- [X] 我是为了提交Issue才选择了上述选框，我不知道我在做什么

### BUG 描述

系统: ImmortalWrt 23.05.4 r28061-399f9a1db3

点击`打开面板`打开的链接: `http://openwrt.lan:9090/ui/metacubexd/?host=openwrt.lan&hostname=openwrt.lan&port=9090&secret=621911#/setup`
会进入到
![image](https://github.com/user-attachments/assets/da8c0500-8271-4b3c-a90d-b25d39ef4df6)

使用ip而不是域名访问也是如此

### 预期行为

能打开面板

### 复现步骤

按教程安装, 上传本地配置文件后启动

### 插件日志

发现没有相关的日志信息

### 核心日志

发现没有相关的日志信息, 日志级别为debug, 清空日志后刷新: 
```
time="2024-12-23T06:20:03.221103182+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-23T06:20:03.224143503+08:00" level=debug msg="[DNS] cache hit in02.graniterapids.com --> [211.99.97.61] A, expire at 2024-12-23 06:21:36"
time="2024-12-23T06:20:03.247270908+08:00" level=info msg="[TCP] 192.168.11.116:14339 --> clients4.google.com:443 match DomainKeyword(google) using 🚀 节点选择[中国-印度 IPLC B02 孟买]"
time="2024-12-23T06:20:04.598344795+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-23T06:20:04.600491745+08:00" level=debug msg="[DNS] cache hit in02.graniterapids.com --> [211.99.97.61] A, expire at 2024-12-23 06:21:36"
time="2024-12-23T06:20:04.626832594+08:00" level=info msg="[TCP] 192.168.11.116:14342 --> clients4.google.com:443 match DomainKeyword(google) using 🚀 节点选择[中国-印度 IPLC B02 孟买]"
time="2024-12-23T06:20:05.989384521+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-23T06:20:05.991835386+08:00" level=debug msg="[DNS] cache hit in02.graniterapids.com --> [211.99.97.61] A, expire at 2024-12-23 06:21:36"
time="2024-12-23T06:20:06.018637692+08:00" level=info msg="[TCP] 192.168.11.116:14343 --> clients4.google.com:443 match DomainKeyword(google) using 🚀 节点选择[中国-印度 IPLC B02 孟买]"
time="2024-12-23T06:20:07.381549789+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-23T06:20:07.383818946+08:00" level=debug msg="[DNS] cache hit in02.graniterapids.com --> [211.99.97.61] A, expire at 2024-12-23 06:21:36"
time="2024-12-23T06:20:07.409539174+08:00" level=info msg="[TCP] 192.168.11.116:14345 --> clients4.google.com:443 match DomainKeyword(google) using 🚀 节点选择[中国-印度 IPLC B02 孟买]"
```

### 附加信息

![image](https://github.com/user-attachments/assets/af4fb177-d817-4e4f-80b6-650d62440bde)

似乎是`http://openwrt.lan:9090//version` 连续 // 导致的?

**Comment by xuhuanzy** [comment]
改掉 // 后正常了

**Comment by xuhuanzy** [comment]
可能是我用 nginx 替代了 uhttpd, 且不强制重定向https导致的?

**Comment by xuhuanzy** [comment]
> 你是怎么改掉的//？

f12本地替换代码，那句代码仅在初始化时调用

**Comment by xianren78** [comment]
这个问题似乎就是我在arm64上遇到的那个手动通过面板更新，导致mihomo版本号不显示然后无法启动的问题。

**Comment by xuhuanzy** [comment]
面板代码的问题, 我看了他的源码, 似乎已经修复了但没发布
