### ISSUE TITLE
WAN接口获取错误

### ISSUE THREAD

**Issue by JohnsonRan** [morytyann/OpenWrt-mihomo#36]
接 #34 我添加了一个SFP接口用来访问我的猫棒。重启之后插件似乎把SFP接口当成出口导致上面问题
是否有办法加一个选择接口的地方呢
虽然[mihomo](https://wiki.metacubex.one/en/config/general/#outbound-interface)可以设置，但是会导致用同配置的其他设备出现问题吧（

**Comment by morytyann** [comment]
1. 我使用`/lib/functions/network.sh`的`network_find_wan`函数来获取WAN接口，这可能是BUG，也有可能是预期的行为。
2. luci-app-upnp也有类似的问题
3. 插件可以通过添加一个用于配置WAN接口的配置项，以此来缓解这个问题
4. 同时此选项可以解决多WAN情况下无法选择出口的问题

**Comment by morytyann** [comment]
你是想可以上网的同时访问光猫/猫棒？可以通过这样设置暂时规避这个问题，只要不勾选访问光猫/猫棒的接口配置中的使用默认网关就可以了

**Comment by JohnsonRan** [comment]
之前是跃点设置成99，刚刚取消勾选使用默认网关，重启后还是会刷wanring

**Comment by morytyann** [comment]
我这里有IPTV的接口，刚才测试了，如果开启默认网关，就会获取到IPTV的接口，关闭了就正常。
然后我又添加了光猫的接口，测试也是一样的结果。

> 之前是跃点设置成99，刚刚取消勾选使用默认网关，重启后还是会刷wanring

**Comment by morytyann** [comment]
我在代理配置中添加了`WAN 接口`选项，会在安装后执行脚本自动设置，如果获取的不正确，在选项自行修正即可。

**Comment by JohnsonRan** [comment]
> 我这里有IPTV的接口，刚才测试了，如果开启默认网关，就会获取到IPTV的接口，关闭了就正常。 然后我又添加了光猫的接口，测试也是一样的结果。
> 
> > 之前是跃点设置成99，刚刚取消勾选使用默认网关，重启后还是会刷wanring

之前我也没问题，昨天更新了23.05.4，可能是某些地方改了吧？懒得管了
