### ISSUE TITLE
手动更新订阅功能按钮

### ISSUE THREAD

**Issue by JohnsonRan** [morytyann/OpenWrt-mihomo#39]
~~帮群友提的~~
目前更新订阅只能通过重新启用插件来实现，虽然更新配置确实需要重启mihomo，但通过一个按钮来进行会更方便一些？

**Comment by morytyann** [comment]
1. 每次启动时都会重新下载的订阅的配置文件
2. 因此，定时重启也可以作为定时更新订阅使用
3. 需要手动更新的情况很少
4. 系统 -> 启动项，可以重启任意服务，重启即可更新订阅

**Comment by morytyann** [comment]
还是加上了重启按钮，可以通过它来更新订阅
