### ISSUE TITLE
希望可以提供无覆盖的纯配置文件运行模式

### ISSUE THREAD

**Issue by luestr** [morytyann/OpenWrt-mihomo#4]
对于上传自己编写的配置文件的用户，只想让这个luci当作一个启动器，不想被luci的选项覆盖任何配置文件的内容。

所以，希望以下内容可以不对【上传配置文件】模式做任何覆盖修改

【全局配置】【入站配置】【DNS配置】【嗅探器配置】【GeoX配置】

麻烦了

**Comment by morytyann** [comment]
在基础配置中添加了开关，关闭后将只混入如下配置

- 外部控制配置的端口和密钥
- 入站配置的端口
- DNS配置的端口
- 路由标记
