### ISSUE TITLE
请求添加在线更新插件功能

### ISSUE THREAD

**Issue by mswarmtree** [morytyann/OpenWrt-mihomo#40]
目前插件更新必须仓库下载上传安装，能否做个类似openclash的在线更新插件和内核功能？

**Comment by morytyann** [comment]
不会在插件添加更新功能，但有计划做一个feed的仓库，届时可以通过添加到`/etc/opkg/distfeeds.conf`来实现在线安装/更新

**Comment by mswarmtree** [comment]
> 不会在插件添加更新功能，但有计划做一个feed的仓库，届时可以通过添加到`/etc/opkg/distfeeds.conf`来实现在线安装/更新

好的，谢谢，辛苦了

**Comment by morytyann** [comment]
kiddin9的[仓库](https://github.com/kiddin9/openwrt-packages)收录了本插件，可以用这个仓库
