### ISSUE TITLE
作者大大 IPV6近期有计划支持吗？

### ISSUE THREAD

**Issue by zhoufla** [morytyann/OpenWrt-mihomo#44]
如题

**Comment by morytyann** [comment]
计划肯定是有的，但不是最近，慢慢来吧，总会填坑的，哈哈

**Comment by morytyann** [comment]
已添加IPv6支持，在[打包](https://github.com/morytyann/OpenWrt-mihomo/actions/runs/10159415149)，等测试没问题了我再合并然后发Release，你也可以先试试，有问题来开ISSUE
