### ISSUE TITLE
文件预下载问题

### ISSUE THREAD

**Issue by pmkol** [morytyann/OpenWrt-mihomo#54]
看到规则有很大变化，而且文件下载的名称貌似也发生了变化，请问新的规则文件会下载到哪里，以及几个规则文件的命名是什么？

**Comment by morytyann** [comment]
插件移除了预下载数据库的逻辑，交给核心自行下载，路径还是mihomo的工作目录下，既`/etc/mihomo/run`
文件名称，其实是核心决定的
GeoSite：GeoSite.dat
GeoIP（DAT格式）：GeoIP.dat
GeoIP（MMDB格式）：Country.mmdb、geoip.db、geoip.metadb （具体是哪个要看你的URL地址）
GeoIP（ASN）：ASN.mmdb

**Comment by pmkol** [comment]
感谢
