### ISSUE TITLE
[BUG]订阅下载的问题。

### ISSUE THREAD

**Issue by liaoke01** [morytyann/OpenWrt-mihomo#57]
我的订阅链接在其他的平台上都可以下载出正确的配置文件,如果直接用浏览器访问这个订阅链接则会出现一串加密字符，而我用mihomo订阅这个链接得到的结果和浏览器访问这个链接的结果是一样的，都是一串加密字符而非正确的配置文件，但是用其他的任何客户端都是可以订阅出正确的配置文件的。

**Comment by liaoke01** [comment]
将从其他客户端上订阅下来的文件手动上传就可以正常启动了，但是使用订阅就会出现全是加密字符串而非正确的配置文件的问题，请麻烦修一下。

**Comment by morytyann** [comment]
加密的？大概是BASE64吧，机场应该是返回了的Shadowsocks的订阅，知道了，应该是下载的时候没有指定UserAgent的问题。

**Comment by morytyann** [comment]
着急使用订阅的话，可以看看机场的订阅链接有没有参数可以指定格式，手动指定Clash格式，我这边也会处理。

**Comment by liaoke01** [comment]
> 着急使用订阅的话，可以看看机场的订阅链接有没有参数可以指定格式，手动指定Clash格式，我这边也会处理。

这个机场支持手动指定，但是我手动指定了之后仍然是返回base64,可能是强制检测ua

**Comment by morytyann** [comment]
在[Build](https://github.com/morytyann/OpenWrt-mihomo/actions/runs/10301574201)了，一会试试这个

**Comment by morytyann** [comment]
我先关闭ISSUE了，还有问题请Reopen，感谢❤️
