### ISSUE TITLE
[BUG] 混入文件输入框的问题

### ISSUE THREAD

**Issue by ForestL18** [morytyann/OpenWrt-mihomo#59]
**Describe the bug**
混入文件输入框的问题如下：

1. 每次升级插件的时候，输入框内容会消失，应该是每次升级mixin.yaml被覆盖成空文件。

2. 每次修改混入文件的内容，点击保存并应用后并不会立即写入配置文件生效，luci界面显示没有要更改的内容。必须重启插件或者点击保存编辑器里的配置文件才能生效。

**To Reproduce**
如上

**Expected behavior**
1. 每次升级插件时应保留mixin.yaml，使其不被覆盖

2. 每次修改完混入文件内容后，点击保存应用后应立即生效

**Enviroment (please complete the following information):**
 - OS: [ImmortalWrt]
 - Version [23.05.3]
 - Architecture [aarch64_generic]

**Additional context**
对于 `IPv4/IPv6 DNS 劫持 `，当**仅**选择`IPv4 DNS 劫持`时应当给出提示或警告：可能会产生DNS污染或分流错误

**Comment by morytyann** [comment]
保留mixin.yaml好说，立即生效不好弄，如果在保存文件后reload服务，假设有其他的更改，也会触发reload，会reload两次，除非移动到编辑器（不太想移动，因为这是混入配置，在现在的位置比较合理），修改一下编辑器标签页，添加一个保存并应用按钮，在这里触发一下reload

DNS劫持的提醒，我加到Wiki吧

**Comment by morytyann** [comment]
我在v1.5.3分支的编辑器里添加了编辑`用于混入的文件`功能，也添加了保存并应用按钮（选择保存并应用会触发reload，选择强制应用触发restart，也相当于添加了重载/重启按钮）
Wiki明天更新

**Comment by morytyann** [comment]
#61 不行的，我说的reload两次一次是保存文件时的reload，另一次是uci触发的reload，和profile_watcher没有关系的

**Comment by morytyann** [comment]
当时加入profile_watcher时为了不添加重载/重启按钮，现在有符合逻辑的重载/重启按钮了，自然就去掉了

**Comment by morytyann** [comment]
Wiki已更新，同步最新版本的配置项，添加了[关于DNS劫持的说明](https://github.com/morytyann/OpenWrt-mihomo/wiki#%E5%85%B3%E4%BA%8Edns%E5%8A%AB%E6%8C%81%E7%9A%84%E8%AF%B4%E6%98%8E)
