### ISSUE TITLE
安装昨天的插件后luci界面报错

### ISSUE THREAD

**Issue by luestr** [morytyann/OpenWrt-mihomo#6]
1. 全新写盘的x86固件，不是升级上来的，所以不存在老系统残留问题；
2. 使用的ipk是仓库里最新版本的；
3. 内核版本为5.15.158

<img width="330" alt="Snipaste_2024-06-23_19-12-38" src="https://github.com/morytyann/OpenWrt-mihomo/assets/152216177/2e692e9b-d3e8-43a0-ae3e-b510ad4316c7">

**Comment by morytyann** [comment]
没有测试到全新安装的情况，已修复

**Comment by morytyann** [comment]
试试清一下浏览器缓存
