### ISSUE TITLE
混入文件问题

### ISSUE THREAD

**Issue by qcyhub** [morytyann/OpenWrt-mihomo#62]
对于很多初次接触者而言，混入文件的大白框是有点无所适从的，
建议增加注释的示例。比如像openclash的自定义规则里的示例。

可以按可以混入的内容分几个大类，分别举例。
这样对很多初次接触者会比较友好，

另外一个就是作者不想加的功能更新订阅 或者说重启按钮，我第一次接触或者别人的反馈都是因为这个而没有进一步的去使用验证，
毕竟不是每个人都会来看github，虽然稳定运行后不需要手动去管他，但是测试订阅以及瞎折腾的人非常多，我代表我知道的一些需要增加的投一票吧。

另外非常感谢作者制作了这么棒的插件，真的太棒了，解决了openclash的臃肿繁杂问题
简约而不简单，我会在我电报群和视频中进行推广，再次由衷的感谢作者！

**Comment by morytyann** [comment]
> 混入文件内容的示例

我还真不知道该添加什么示例内容，能比较有效的提示如何使用这个配置项

> 重启/更新订阅按钮

哈哈，真的有第三个人来提了，我还是添加上吧

> 不是每个人都会来看GitHub

我在插件LuCI界面添加一个使用说明指向Wiki吧，Wiki的说明还是比较详细的，我也打算一直维护这个Wiki

**Comment by qcyhub** [comment]
感谢这么快的回复，

比如以下方式：
最上方是说明此配置项的目的，以及可以添加哪些内容。
下方是举几个常用到的示例，其他不常用的示例可以放到wiki中，根据大家的问题持续增加维护。
另外混入这个词一眼不是能够直接理解，是不是叫覆盖或者覆写配置好一些啊，受openclash影响太深 哈哈。

script:
##  shortcuts:
##    Notice: The core timezone is UTC
##    CST 20:00-24:00 = time.now().hour > 12 and time.now().hour < 16
##    内核时区为UTC,故以下time.now()函数的取值需要根据本地时区进行转换
##    北京时间(CST) 20:00-24:00 = time.now().hour > 12 and time.now().hour < 16
##    quic: network == 'udp' and dst_port == 443 and (geoip(resolve_ip(host)) != 'CN' or geoip(dst_ip) != 'CN')
##    time-limit: in_cidr(src_ip,'192.168.1.2/32') and time.now().hour < 20 or time.now().hour > 21
##    time-limit: src_ip == '192.168.1.2' and time.now().hour < 20 or time.now().hour > 21

##  code: |
##    def main(ctx, metadata):
##        directkeywordlist = ["baidu"]
##        for directkeyword in directkeywordlist:
##          if directkeyword in metadata["host"]:
##            ctx.log('[Script] matched keyword %s use direct' % directkeyword)
##            return "DIRECT"

rules:
##- SCRIPT,quic,REJECT #shortcuts rule
##- SCRIPT,time-limit,REJECT #shortcuts rule

##- PROCESS-NAME,curl,DIRECT #匹配路由自身进程(curl直连)
##- DOMAIN-SUFFIX,google.com,Proxy #匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy #匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy #匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT #匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT #匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT #匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT #匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT #匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除

##仅设置路由器自身直连：
##- SRC-IP-CIDR,192.168.1.1/32,DIRECT
##- SRC-IP-CIDR,198.18.0.1/32,DIRECT

##DDNS
##- DOMAIN-SUFFIX,checkip.dyndns.org,DIRECT
##- DOMAIN-SUFFIX,checkipv6.dyndns.org,DIRECT
##- DOMAIN-SUFFIX,checkip.synology.com,DIRECT
##- DOMAIN-SUFFIX,ifconfig.co,DIRECT
##- DOMAIN-SUFFIX,api.myip.com,DIRECT
##- DOMAIN-SUFFIX,ip-api.com,DIRECT
##- DOMAIN-SUFFIX,ipapi.co,DIRECT
##- DOMAIN-SUFFIX,ip6.seeip.org,DIRECT
##- DOMAIN-SUFFIX,members.3322.org,DIRECT

##在线IP段转CIDR地址：http://ip2cidr.com

**Comment by qcyhub** [comment]
可能我的举例内容不恰当，我只想说明这种形式。

**Comment by morytyann** [comment]
已在v1.6.0更新并[Build](https://github.com/morytyann/OpenWrt-mihomo/actions/workflows/build.yml)，可以先试试，我自己也将测试一段时间然后合并和发布Release。

**Comment by qcyhub** [comment]
感谢
