### ISSUE TITLE
订阅功能

### ISSUE THREAD

**Issue by qcyhub** [morytyann/OpenWrt-mihomo#63]
建议把订阅配置模块 模仿openclash 实现 订阅链接 、后端 、以及规则模板分离填写，虽然一条订阅链接也可以实现，
但是后端和规则地址一般是不变的，单纯订阅连接变更的频率要大很多，使用（后端+指定clash+订阅+规则+参数）组合形式的连接，每次去替换中间的订阅订阅连接还需要做url转换，就显得比较麻烦。
或者现有模式 组合连接不需要做url转换实现也可以。

不知道我描述的是否清晰，如有模糊的地方我再补充。

感谢作者！

**Comment by morytyann** [comment]
实际上是添加订阅转换功能是吧，可以的

**Comment by qcyhub** [comment]
是的，如openclash的订阅部分做的比较不错可以借鉴
目前的订阅部分太简单了，不明白的人估计会认为只能简单的订阅什么都不能做。
虽然都可以做到，就像我上面说的比较麻烦。
另外youtube视频我已制作完成 发布后粉丝反馈多的部分 我再提交。
![image](https://github.com/user-attachments/assets/b60bb6ce-e0b3-49ac-a9dd-98f67b32ccbe)

**Comment by morytyann** [comment]
已在v1.6.0更新并[Build](https://github.com/morytyann/OpenWrt-mihomo/actions/workflows/build.yml)，可以先试试，我自己也将测试一段时间然后合并和发布Release。

**Comment by qcyhub** [comment]
感谢！
