### ISSUE TITLE
[Feature Request] 使用 Alpha 分支的 mihomo

### ISSUE THREAD

**Issue by zutzo** [morytyann/OpenWrt-mihomo#64]
rt
正式版更新缓慢 而且 新特性无法及时吃上 
是否能考虑 添加 alpha  分支的 mihomo (

**Comment by morytyann** [comment]
需要试试能不能打包，需要1.23的Go

**Comment by pmkol** [comment]
> 需要试试能不能打包，需要1.23的Go

https://github.com/pmkol/openwrt-gh-action-sdk 参考或使用我的SDK编译即可使用golang 1.23

**Comment by morytyann** [comment]
v1.7.0开始使用Alpha分支的Mihomo构建。

注：仓库的Build和Release还是使用官方Action进行打包，这意为着Go版本为1.21，不过可以正常运行。如有特殊需要（例如想使用Go1.22/1.23才支持的新特性）请自行构建。不过OpenWrt/packages那边已经有人在提PR更新Go版本了，耐心等待其合并也是可以的。

**Comment by morytyann** [comment]
现在在Build了，烦请帮忙测试一下。
