### ISSUE TITLE
管理面板排列顺序

### ISSUE THREAD

**Issue by yarnme** [morytyann/OpenWrt-mihomo#67]
能否把节点管理web面板调整到最前面来，每次切换节点都要划到最下面，才能打开控制面板非常的不方便。希望作者能优化一下。可以类似open clash这种调整方式，谢谢🙏
![IMG_6728](https://github.com/user-attachments/assets/b0cfb218-1b47-4741-856f-de6ef307c1a8)

**Comment by qcyhub** [comment]
支持，复议！！另外群友反馈第一眼看上去页面比较简陋，可能您主要是适配openwret默认主题，但是大多数用户应该还是用的蓝天白云的左右栏结构，不知道作者是否把上下结构列表改变为左右结构，当然这是次要的。

**Comment by morytyann** [comment]
👌会调整按钮的位置，页面结构的话暂时不调整了

**Comment by qcyhub** [comment]
我建议：
1、把订阅配置模块和基础配置模块合并，毕竟上传yaml和订阅其实是一回事。这样上下的长度会进一步缩短，提高页面在左右栏主题下的美观度，
2、在您考虑调整管理面板的位置的时候建议同步 在状态栏目增加显示具体 流量 cpu 内存  等占用基本信息 会进一步提高美观度。
这条我是觉得没啥用，但是小白用户太多。。。
3、建议把插件运行日志的英文汉化为中文输出，openclash在这方面做的不错可以借鉴，会进一步提高用户好感。

以上不是个人需求，结合粉丝反馈以及对插件长远考虑，感谢作者。

**Comment by morytyann** [comment]
1. 我试了，并没有缩减🥲
2. 等着做一个状态页吧
3. 做状态页的时候一起吧

另外非常感谢你的推广❤️
