### ISSUE TITLE
界面上的设置是必要的吗

### ISSUE THREAD

**Issue by yifai** [morytyann/OpenWrt-mihomo#69]
使用自已写的配置文件，配置文件很完整，导入openclash或clash meta启动即可，在mihomo界面上的设置还需动吗？

**Comment by morytyann** [comment]
如果你不想插件修改你的配置文件，关闭混入即可，但注意一些必要配置还是会混入，详见Wiki

**Comment by morytyann** [comment]
上传好文件后，不修改任何配置也是可以启动和代理的，就像其他的代理软件一样

**Comment by qcyhub** [comment]
作者我想借此询问下，是否有单独出一个，或者在此基础上增加对singbox内核的支持，我看您的简约思维非常适合singbox，目前singbox在openwrt上非常需要一款基于纯粹规则的简单的luci界面，目前的那个唯一的homeproxy，不是纯粹基于规则，反人类，虽然直接运行内核也可以，但是还是不太方便，希望得到您的回复。

**Comment by morytyann** [comment]
不会做的，首先我没用过singbox也没用过homeproxy，其次也是没有这么多精力来维护两个项目🥲

**Comment by qcyhub** [comment]
嗯 好的

**Comment by morytyann** [comment]
感谢Issue
