### ISSUE TITLE
[Feature Request]希望添加指定本地ip地址绕过核心的功能

### ISSUE THREAD

**Issue by Kryo123456** [morytyann/OpenWrt-mihomo#71]
**Is your feature request related to a problem? Please describe.**
家里有服务暴露在公网，发现开启代理服务后无法从公网访问，把tcp代理端口改成常用端口后暂时解决。

**Describe the solution you'd like**
添加指定ip地址绕过核心的功能，如图所示。
![屏幕截图 2024-08-15 213952](https://github.com/user-attachments/assets/3c657ef2-295a-42fc-b58c-4695e0fce00f)

**Describe alternatives you've considered**
因为我所有服务都是通过反代暴露在特定端口，但是我研究了一下没找到使某个特定端口（或者端口范围）绕过核心的功能，如果能添加此功能也可以解决上述问题。

**Additional context**
也有可能是有使某个特定端口（或者端口范围）绕过核心的功能但是我不知道，如果是的话请大佬教教我，谢谢！

**Comment by morytyann** [comment]
本地地址默认绕过的，防火墙的端口转发也是会绕过的，请问你的服务是如何暴露的？我也有服务运行在内网NAS，通过端口转发暴露出去的，一直都是正常访问的。

**Comment by Kryo123456** [comment]
> 本地地址默认绕过的，防火墙的端口转发也是会绕过的，请问你的服务是如何暴露的？我也有服务运行在内网NAS，通过端口转发暴露出去的，一直都是正常访问的。

我在内网的其他服务器上搭建了一个docker，然后在docker里面运行了一个反向代理程序lucky，并在20000端口开启反向代理服务，用它来反代docker里面的其他服务。同时我在路由器的防火墙内允许了wan到该服务器20000端口的流量。我要不要把防火墙的配置发给你看呀？

**Comment by morytyann** [comment]
> 同时我在路由器的防火墙内允许了Wan到该服务器20000端口的流量

这个是怎么配置的？`防火墙 -> 端口转发`？

**Comment by Kryo123456** [comment]
> > 同时我在路由器的防火墙内允许了Wan到该服务器20000端口的流量
> 
> 这个是怎么配置的？`防火墙 -> 端口转发`？

如图所示，不过实际地址不是这个。
<img width="1060" alt="屏幕截图 2024-08-15 221457" src="https://github.com/user-attachments/assets/8330fe52-c9d7-46a4-aaf4-1b78b3a16739">

**Comment by morytyann** [comment]
明白了，会修复这个问题，目前绕过防火墙规则没有考虑到这种情况

**Comment by morytyann** [comment]
话说如果你的IPv6地址变动了怎么办呢？OpenWrt支持后缀匹配吗？

**Comment by Kryo123456** [comment]
> 话说如果你的IPv6地址变动了怎么办呢？OpenWrt支持后缀匹配吗？

可以用反掩码的方式匹配ipv6的后缀，后缀一般根据mac地址生成的不会变更。

**Comment by morytyann** [comment]
学习了

**Comment by morytyann** [comment]
你有设置`代理配置 -> 绕过 -> Wan6 接口`吗，设置一下再看看呢？

**Comment by Kryo123456** [comment]
> 你有设置`代理配置 -> 绕过 -> Wan6 接口`吗，设置一下再看看呢？

我试试看哈。

**Comment by Kryo123456** [comment]
> 你有设置`代理配置 -> 绕过 -> Wan6 接口`吗，设置一下再看看呢？

没有作用诶。

**Comment by morytyann** [comment]
嗯嗯，我在v1.6.1添加了自动绕过`防火墙 -> 通信规则`中转发的项目，在[Build](https://github.com/morytyann/OpenWrt-mihomo/actions/workflows/build.yml)了，麻烦你测试下吧

**Comment by Kryo123456** [comment]
> 嗯嗯，我在v1.6.1添加了自动绕过`防火墙 -> 通信规则`中转发的项目，在[Build](https://github.com/morytyann/OpenWrt-mihomo/actions/workflows/build.yml)了，麻烦你测试下吧

好像还是不行啊，还是不通。

**Comment by morytyann** [comment]
`nft list set inet mihomo redirect_exclusion6`，看下有没有你配置的IP和端口？

**Comment by Kryo123456** [comment]
> `nft list set inet mihomo redirect_exclusion6`，看下有没有你配置的IP和端口？

table inet mihomo {
	set redirect_exclusion6 {
		type inet_proto . ipv6_addr . inet_service
		flags interval
		auto-merge
	}
}
这个提示应该是没有吧。

**Comment by morytyann** [comment]
好吧，明天再说吧

**Comment by Kryo123456** [comment]
> 好吧，明天再说吧

辛苦大佬了，或许可以参考下openclash的代码是怎么实现的，我不太懂。

**Comment by morytyann** [comment]
我看了，OpenClash应该也有一样的问题，你之前正常使用应该是OpenClash没有开启IPv6代理。
昨天的修复不生效是因为nftables的集合不支持添加后缀匹配的IPv6地址，OpenWrt防火墙的做法是通过后缀掩码计算然后匹配，我看看能不能处理吧
```
ip6 daddr & ::ffff:ffff:ffff:ffff == ::2e0:4cff:fe68:15 tcp dport 8443 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Test"
ip6 daddr & ::ffff:ffff:ffff:ffff == ::2e0:4cff:fe68:15 udp dport 8443 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Test"
```

**Comment by morytyann** [comment]
暂时无法处理后缀匹配的情况，给你提供三个Workaround吧
1. 在`防火墙 -> 通信规则`处使用全IPv6地址，缺点是前缀变了你需要修改这个规则
2. 关闭IPv6代理，缺点就是没法代理IPv6（感觉这样更能让人接受）
3. 手动添加绕过（这个需要执行命令，如果你会的话这个是最好的，缺点是每次都要自己添加……）

**Comment by Kryo123456** [comment]
> 我看了，OpenClash应该也有一样的问题，你之前正常使用应该是OpenClash没有开启IPv6代理。 昨天的修复不生效是因为nftables的集合不支持添加后缀匹配的IPv6地址，OpenWrt防火墙的做法是通过后缀掩码计算然后匹配，我看看能不能处理吧
> 
> ```
> ip6 daddr & ::ffff:ffff:ffff:ffff == ::2e0:4cff:fe68:15 tcp dport 8443 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Test"
> ip6 daddr & ::ffff:ffff:ffff:ffff == ::2e0:4cff:fe68:15 udp dport 8443 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Test"
> ```

但是我openclash开了ipv6代理也是能正常从外网访问的。此外我早上重新测试了下发现mihomo开启绕过中国大陆后也能正常从外网访问，不过我不太理解其中的技术原理。

**Comment by morytyann** [comment]
那你有在OpenClash手动添加绕过吗？

**Comment by Kryo123456** [comment]
> 那你有在OpenClash手动添加绕过吗？

没有我openclash没有动过只设置了下dns之类的。
![屏幕截图 2024-08-16 122928](https://github.com/user-attachments/assets/42f795d8-00bb-469b-add8-0ba45bdd854d)
![屏幕截图 2024-08-16 122955](https://github.com/user-attachments/assets/74f84d48-cbd1-4d0f-88c1-5d622ac252e2)
![屏幕截图 2024-08-16 123011](https://github.com/user-attachments/assets/e6c88ff6-8fc7-4617-94a8-96f2652a9891)
![屏幕截图 2024-08-16 123026](https://github.com/user-attachments/assets/ffc9a9ef-6026-4125-9088-586054579f51)

**Comment by zhoufla** [comment]
> 暂时无法处理后缀匹配的情况，给你提供三个Workaround吧
> 
> 1. 在`防火墙 -> 通信规则`处使用全IPv6地址，缺点是前缀变了你需要修改这个规则
> 2. 关闭IPv6代理，缺点就是没法代理IPv6（感觉这样更能让人接受）
> 3. 手动添加绕过（这个需要执行命令，如果你会的话这个是最好的，缺点是每次都要自己添加……）

使用socat转发就行

**Comment by morytyann** [comment]
在v1.6.2换了一种方式来处理，Build中，麻烦你再测试下吧，这一版至少我自己测是正常的，也是用的你的后缀匹配规则来测试的，可以正常访问

**Comment by morytyann** [comment]
绕过返回方向的源地址是WAN/WAN6 IP地址的包，这样甚至不需要处理绕过防火墙规则还有UPnP了。
```
ct reply ip saddr @wan_ip counter return
ct reply ip6 saddr @wan_ip6 counter return
```

**Comment by Kryo123456** [comment]
> 绕过返回方向的源地址是WAN/WAN6 IP地址的包，这样甚至不需要处理绕过防火墙规则还有UPnP了。
> 
> ```
> ct reply ip saddr @wan_ip counter return
> ct reply ip6 saddr @wan_ip6 counter return
> ```

请问这样处理和openclash的方法有什么区别么，有没有什么副作用啊？

**Comment by morytyann** [comment]
目前来看没什么副作用，OpenClash是绕过端口的方式，还需要随防火墙规则更新，本插件之前也是这么做的，不过现在不需要了，直接绕过入站连接的回包就行了。

**Comment by Kryo123456** [comment]
> 目前来看没什么副作用，OpenClash是绕过端口的方式，还需要随防火墙规则更新，本插件之前也是这么做的，不过现在不需要了，直接绕过入站连接的回包就行了。

感谢大佬！我先关闭这个issue了。

**Comment by Kryo123456** [comment]
升级1.6.5后，问题又复现了。

**Comment by morytyann** [comment]
重启下试试……

**Comment by morytyann** [comment]
1.6.5只修改一个和这个没有关系地方……怎么会影响到呢😢

**Comment by Kryo123456** [comment]
> Owner
我把我所有的设备全部重启了下，情况依旧。回退到1.6.4之后恢复正常。

**Comment by Kryo123456** [comment]
> 1.6.5只修改一个和这个没有关系地方……怎么会影响到呢😢

我把我所有的设备全部重启了下，情况依旧。回退到1.6.4之后恢复正常。

**Comment by Kryo123456** [comment]
> 你重新下载一下仓库的1.6.4的Release试试，如果不正常的话我就知道为什么了。

https://github.com/morytyann/OpenWrt-mihomo/releases/download/v1.6.4/mihomo_x86_64.tar.gz请问是这个么？

**Comment by Kryo123456** [comment]
> 你重新下载一下仓库的1.6.4的Release试试，如果不正常的话我就知道为什么了。

重新下载1.6.4之后确实也不行了，所以是什么原因呢。

**Comment by morytyann** [comment]
编辑`/etc/init.d/mihomo`，将最下面的`add_wan6_inbound_exclusion`替换成下面这段，再试下？
```shell
add_wan6_inbound_exclusion() {
	local wan6_ips wan6_ip
	network_get_ipaddrs6 wan6_ips $1
	if [ -n "$wan6_ips" ]; then
		for wan6_ip in $wan6_ips; do
			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_ip" \}
		done
	fi
	local wan6_subnets wan6_subnet
	network_get_subnets6 wan6_subnets $1
	if [ -n "$wan6_subnets" ]; then
		for wan6_subnet in $wan6_subnets; do
			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_subnet" \}
		done
	fi
	local wan6_prefixes wan6_prefix
	network_get_prefixes6 wan6_prefixes $1
	if [ -n "$wan6_prefixes" ]; then
		for wan6_prefix in $wan6_prefixes; do
			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_prefix" \}
		done
	fi
}
```

**Comment by Kryo123456** [comment]
> 编辑`/etc/init.d/mihomo`，将最下面的`add_wan6_inbound_exclusion`函数替换成下面这段再试下。
> 
> ```shell
> add_wan6_inbound_exclusion() {
> 	local wan6_ips wan6_ip
> 	network_get_ipaddrs6 wan6_ips $1
> 	if [ -n "$wan6_ips" ]; then
> 		for wan6_ip in $wan6_ips; do
> 			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_ip" \}
> 		done
> 	fi
> 	local wan6_subnets wan6_subnet
> 	network_get_subnets6 wan6_subnets $1
> 	if [ -n "$wan6_subnets" ]; then
> 		for wan6_subnet in $wan6_subnets; do
> 			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_subnet" \}
> 		done
> 	fi
> 	local wan6_prefixes wan6_prefix
> 	network_get_prefixes6 wan6_prefixes $1
> 	if [ -n "$wan6_prefixes" ]; then
> 		for wan6_prefix in $wan6_prefixes; do
> 			nft add element inet $FW_TABLE wan_ip6 \{ "$wan6_prefix" \}
> 		done
> 	fi
> }
> ```

添加并重启mihomo服务后还是没有用。

**Comment by morytyann** [comment]
那我就不知道了，你自己对比下找找原因？没有其他的修改了……

**Comment by morytyann** [comment]
所以还是需要改这个函数才能正常是吧？

**Comment by Kryo123456** [comment]
> 所以还是需要改这个函数才能正常是吧？

没事了，试了下最新版，不用改也行了，不好意思麻烦大佬了。
