### ISSUE TITLE
首次启动困难

### ISSUE THREAD

**Issue by hsiangyeung** [morytyann/OpenWrt-mihomo#73]
安装后首次运行本地网络下载文件困难，启动不成功，需要借助openclash才能成功下载启动，可以优化一下吗？类似于openclash的CDN功能，防止文件下载失败

**Comment by morytyann** [comment]
是指GeoSite/GeoIP数据库文件吗？

**Comment by morytyann** [comment]
![image](https://github.com/user-attachments/assets/6cac30a9-c3d9-4f8c-8f60-de253ac5ee74)如果是GeoX数据库的话，默认就是走ghproxy下载的。可能的网络环境下这个CDN不好用，你可以自己配置下其他的试一试。

**Comment by morytyann** [comment]
没事，用不上不会下载的，而且这些也是Mihomo核心的[默认配置](https://github.com/MetaCubeX/mihomo/blob/4fedfc47b0e968b4b47d102826c463c808172618/config/config.go#L516-L521)，即使不混入也是有值的

**Comment by hsiangyeung** [comment]
> ![图像](https://private-user-images.githubusercontent.com/10665459/358424087-6cac30a9-c3d9-4f8c-8f60-de253ac5ee74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzY0MjUsIm5iZiI6MTcyMzc3NjEyNSwicGF0aCI6Ii8xMDY2NTQ1OS8zNTg0MjQwODctNmNhYzMwYTktYzNkOS00ZjhjLThmNjAtZGUyNTNhYzVlZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAyNDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzY4YTE5MTk1MTE4YTg4ZmMzMTBiMjQ0MjcxNGU2ZTNmZjNlMDJkOTk3ZTI3NTMxMGU0NDUzYjhlM2YwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5CY8ptx70dq9tKU7xf-L7uzmMFbfkNOJ4c1rwyeNgY)如果是GeoX数据库的话，默认就是走ghproxy下载的。可能这个CDN下的网络环境不好用，你可以自己配置下其他的试一试。

目前把WAN口使用自定义DNS1.1.1.1 可以下载成功了  ，刚刚更新最新1.61版   发现外部访问控制 面板的打开按钮消失了，现在进不去面板

![1](https://github.com/user-attachments/assets/c06298f5-c936-4303-b684-e3a40bb3cb19)

**Comment by morytyann** [comment]
好的。面板按钮现在在状态那里，往上滑找找。

**Comment by hsiangyeung** [comment]
> 好的。面板按钮现在在状态那里，往上滑找找。

太感谢了，眼盲才看到

**Comment by morytyann** [comment]
嗯嗯，没问题了的话先关了，感谢Issue❤️
