### ISSUE TITLE
[Feature Request] 关于管理面板功能的变更

### ISSUE THREAD

**Issue by morytyann** [morytyann/OpenWrt-mihomo#75]
目前来看，似乎并没有同时使用多个面板的必要性，可以考虑移除razord和yacd面板或者只允许选择一个面板使用，这样的话还可以通过调用核心的API来更新面板

如果你赞同移除razord和yacd面板的话请点👍，赞同只选一个面板请点❤️，不赞同的话请点👎

**Comment by zhoufla** [comment]
支持移除，保留一个面板即可。配置文件可以配置ui的下载路径，有需要自行更换即可。

**Comment by Mikihta** [comment]
一个面板足够了，如果可以的话甚至可以将这个面板直接放在openwrt里服务菜单下，提供一个面板切换菜单即可

**Comment by qaz69** [comment]
个人喜欢yacd面板，稳定流畅…无bug

**Comment by morytyann** [comment]
嗯，众口难调，不过鉴于投票移除Razord和YACD的人多，还是决定不再直接支持这两个面板，将修改`混入配置 -> 外部控制`，具体变更如下：
1. 移除三个面板的选择框
2. 添加UI名称配置项，默认metacubexd，可自行配制，将混入配置文件
3. 添加UI下载地址配置项，默认为MetaCubeXD的地址，可自行配制，将混入配置文件
4. 如UI下载地址使用了MetaCubeXD的地址，此时打开面板可以正常连接到后端，无需手动配置
5. 如UI下载地址使用了YACD或Razord的地址，此时打开面板无法直接连接到后端，请手动配置
6. 无论用哪个面板的下载地址，都可以通过API更新面板，其中MetaCubeXD面板提供了更新按钮，更加方便一些

**Comment by morytyann** [comment]
在v1.6.3完成了变更，不过引入了一个问题，初次安装v1.6.3或者修改面板地址后需要点击更新面板按钮才可以更新，不过上游有一个[变更](https://github.com/MetaCubeX/mihomo/commit/50d0cd363c84c14a4982731d24082e0ee65265f0)，将支持自动下载面板，待其发布后就不会有这个问题了。
