### ISSUE TITLE
[BUG]使用luci-theme-argon主题还是显示的老的排版

### ISSUE THREAD

**Issue by ace115** [morytyann/OpenWrt-mihomo#76]
ImmortalWrt SNAPSHOT r31323-288bb4facc 
![屏幕截图 2024-08-16 121219](https://github.com/user-attachments/assets/e0c21925-7914-4586-9511-9809ada57007)
![屏幕截图 2024-08-16 121250](https://github.com/user-attachments/assets/66514630-b1b7-410e-aa67-b64173f1d09a)

切换成其他主题均能正常显示

**Comment by morytyann** [comment]
清一下浏览器缓存就好了
