### ISSUE TITLE
怀疑绕过WAN6接口获取到的ipv6地址不正确

### ISSUE THREAD

**Issue by H2295** [morytyann/OpenWrt-mihomo#77]
ip地址如下图：
![image](https://github.com/user-attachments/assets/6dc70792-369d-46a9-85ea-81947db7c7dd)
执行   nft list set inet mihomo wan_ip6
table inet mihomo {
        set wan_ip6 {
                type ipv6_addr
                flags interval
                auto-merge
                elements = { ****:****:5e02:6fb0::/60 }
        }
}
它自动识别的是ipv6-pd的地址，正常是要****:****:5e80:68a0:64af:****:****:****/64这个地址才对吧？

**Comment by morytyann** [comment]
PD是对的，如果不是PD，那么入站访问局域网IPv6的流量就会被代理了，不像IPv4只考虑路由器即可

**Comment by H2295** [comment]
好的，谢谢解答

**Comment by morytyann** [comment]
❤️

**Comment by morytyann** [comment]
抱歉，我之前一直以为IPv6-PD地址包含了IPv6地址，现在看来不是，不过我已经修改了，将它们都添加到wan_ip6集合了。
