### ISSUE TITLE
[BUG] 打开Razord，提示404 page not found

### ISSUE THREAD

**Issue by gygy** [morytyann/OpenWrt-mihomo#78]
配置已开启。
打开Razord，提示404 page not found

**Comment by morytyann** [comment]
有保存并应用配置吗？

**Comment by gygy** [comment]
> 有保存并应用配置吗？

确认保存应用了。其他2个面板可以打开。就：打开Razord，提示404 page not found

**Comment by gygy** [comment]
> 禁用Razord 保存并应用 启用Razord 保存并应用，这样试试呢，可能是下载失败了

测试过了，无效

**Comment by morytyann** [comment]
不能复现呢
![image](https://github.com/user-attachments/assets/976c6509-6710-41c7-a4f1-53b588acb649)

**Comment by morytyann** [comment]
删除`/etc/mihomo/run/ui/`下的所有内容（保留ui文件夹），然后重启下再看看呢

**Comment by gygy** [comment]
> 删除`/etc/mihomo/run/ui/`下的所有内容（保留ui文件夹），然后重启下再看看呢

无效。 重启后，文件夹的文件会恢复。但依然打不开。
![image](https://github.com/user-attachments/assets/ef794512-859c-4440-81c0-4da932db35a5)

**Comment by morytyann** [comment]
打开的页面截个图，顺便发一下地址栏的链接

**Comment by morytyann** [comment]
![image](https://github.com/user-attachments/assets/447bdd31-b9ba-435f-b84a-5042d777f549)
文件是一样的，那应该是链接不对了（除非是核心的问题，不过应该不会，就是个Web服务器而已）

**Comment by gygy** [comment]
> ![image](https://private-user-images.githubusercontent.com/10665459/358582315-447bdd31-b9ba-435f-b84a-5042d777f549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTIyNjEsIm5iZiI6MTcyMzgxMTk2MSwicGF0aCI6Ii8xMDY2NTQ1OS8zNTg1ODIzMTUtNDQ3YmRkMzEtYjliYS00MzVmLWI4NGEtNTA0MmQ3NzdmNTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyMzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZTJmMGRhYzZjYTBjMTIyMjBmZWQzMTNhNzU0YTBhNTI1ZWQ3MDNmMjQ0ZDA5MzEyYWMwN2M2NmRhZWJiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8aL407IPUBhyyr6tDgY0yin5zr0DHDpe4WYxiF6QLk) 文件是一样的，那应该是链接不对了（除非是核心的问题，不过应该不会，就是个Web服务器而已）
解决了。我关闭Openclash，重启后 可以了。 可能和OC冲突了。
