### ISSUE TITLE
[Feature Request] 建议添加一个国内国外链接是否通 及ping值的状态图

### ISSUE THREAD

**Issue by gygy** [morytyann/OpenWrt-mihomo#79]
建议添加
1、网站访问检查一个国内国外链接是否通 及ping值的状态图
2、国内外IP地址显示

**Comment by Kryo123456** [comment]
这种我个人觉得没必要加在插件里，随便找个测试网站都有这种功能。

**Comment by gygy** [comment]
这个插件最大的问题，显示已经在运行了，但用户不知道是否真正成功了？ 参考oc 及pw ，都有这个功能，一目了然。 如果不成功，网络都有问题，怎么访问一个查看网站？

**Comment by gygy** [comment]
> 简单的事情 没有 必要 复杂化 启动了 必然 是通过了 插件的 启动前测试 启动后 用户 应该 自行 前往代理面板 进行 选择节点 操作 而不是盯着 luci 在 luci 添加 连通性测试 纯属多余

界面显示 正在运行。但用户访问不了国内、国外的网站。启动了，就没有问题了？

**Comment by gygy** [comment]
![image](https://github.com/user-attachments/assets/3eb0b2d2-6639-4544-aa90-350e4ed8f100)
可视学习下oc，一目了然，而不是去跑去日志或面板分析。前面状态显示正常，95%基本不会没事看日志 或面板。

**Comment by morytyann** [comment]
很抱歉一直没有回复。
我想说，也有[HomeProxy](https://github.com/immortalwrt/homeproxy)这种没有类似功能的插件（虽然不及OpenClash和PassWall流行），我在开发之初就是想做一个简洁的插件，不需要那些繁杂的功能，只做好透明代理就好，目前来看用户也是因这个选择试用和使用本插件。而且这个东西，在你出问题（例如你说的无法连通）的时候，无论你有没有能力调试，它其实都没什么太大的作用，还是需要看日志和面板连接。

另外，我曾经也是OpenClash用户，如果我觉得这个好，我可能很早就加上了……

综上，将不会添加连通性测试功能和IP显示。不过还是感谢你的Issue。❤️
