### ISSUE TITLE
[Feature Request]希望能直接从luci界面更新插件

### ISSUE THREAD

**Issue by Kryo123456** [morytyann/OpenWrt-mihomo#82]
**Is your feature request related to a problem? Please describe.**
目前插件处于频繁更新期，在luci界面添加更新功能就不用经常打开github，还要再用opkg更新插件包。

**Describe the solution you'd like**
在luci界面添加一键检查并更新插件功能。

**Comment by morytyann** [comment]
Duplicate of #40
