### ISSUE TITLE
[BUG]初次安装mihomo 1.6.3出现文件和配置显示问题

### ISSUE THREAD

**Issue by Mikihta** [morytyann/OpenWrt-mihomo#83]
**环境**：
- **OpenWRT版本**：[OpenWrt 23.05.4 (r24012-d8dd03c46f)]
- **Mihomo插件版本**：1.6.3
- **设备型号**：GL-iNet MT3000

**问题描述**：
在OpenWRT上初次安装mihomo 1.6.3后，遇到以下问题：
1. 在editor菜单下的Choose Profile选项中，无法显示已上传的文件和通过订阅链接下载的文件，界面仅显示`File:undefined`。
2. 在尝试打开log菜单时，界面无法显示任何信息，并出现以下错误提示：
ReferenceError: uci is not defined

**复现步骤**：
1. 在OpenWRT上安装mihomo 1.6.3版本。
2. 尝试在editor菜单下使用Choose Profile功能。
3. 尝试打开log菜单。

**预期行为**：
- Choose Profile应正确显示已上传的配置文件和通过订阅下载的文件。
- log菜单应能正常显示二级菜单和日志信息。

**实际行为**：
- Choose Profile无法显示文件，界面显示`File:undefined`。
- logo菜单打开时不显示信息，并提示`ReferenceError: uci is not defined`错误。

**尝试的修复**：
- 重新安装mihomo插件。
- 重启设备。
- 重置设备。

希望得到关于如何解决这一问题的建议或解决方案。谢谢！

**Comment by morytyann** [comment]
清下缓存试试？话说logo菜单是什么？

**Comment by morytyann** [comment]
log菜单啊，我也发现了……稍等，我修复一下。

**Comment by morytyann** [comment]
重新发布了v1.6.3版本，一会再试试吧，话说你的那个IPv6的正常了吗

**Comment by morytyann** [comment]
OK，可以了，刚才改了忘了测试了。
