### ISSUE TITLE
[BUG]ReferenceError uci is not defined

### ISSUE THREAD

**Issue by chenzhiguo** [morytyann/OpenWrt-mihomo#84]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/bbf53edc-6a12-45cd-a645-5db84d3db416)

**Enviroment (please complete the following information):**
 - OS: [ImmortalWrt]
 - Version [23.05.3 r27917-81a1f98d5b]
 - Architecture [x86_64]

**Comment by morytyann** [comment]
Duplicate of #83

**Comment by morytyann** [comment]
重新下载安装吧，我修复了然后重新发了Release。

**Comment by chenzhiguo** [comment]
重装了1.6.4，日志还是这样的报错。

**Comment by morytyann** [comment]
清下浏览器缓存

**Comment by chenzhiguo** [comment]
无痕模式试了下，可以了
