### ISSUE TITLE
[BUG]Yacd-meta 和 Razord 面板主页加载失败，需调整跳转 URL 格式

### ISSUE THREAD

**Issue by Mikihta** [morytyann/OpenWrt-mihomo#85]
### Issue 描述

在使用 mihomo 插件时，将面板切换成 Yacd-meta 或 Razord 并更新面板后，打开面板时会跳转到以下网址：
```
http://[hostname]:[port]/ui/[面板名称]/#/setup?hostname=[hostname]&port=[port]&secret=[secret]
```
这个设置在使用 Yacd-meta 和 Razord 面板时会导致界面为空白，因为这两个面板没有提供 `setup` 页面。

### 重现步骤

1. 切换到 Yacd-meta 或 Razord 面板。
2. 更新面板。
3. 打开面板，观察页面跳转的 URL以及页面显示内容。

### 预期行为

页面应该正确加载而不是显示空白。

### 实际行为

Yacd-meta 和 Razord 面板显示空白页面。

### 可能的解决方法

通过将 URL 修改为以下形式可以解决问题：
```
http://[hostname]:[port]/ui/[面板名称]/#/?hostname=[hostname]&port=[port]&secret=[secret]
```
删除 URL 中的 `setup` 部分，可以避免空白页面的出现，同时也不会影响 MetaCubeXD 面板的正常使用。

### 建议

为了提升用户体验，建议在外部控制中增加一个面板选择选项，包括 Yacd-meta、Razord、MetaCubeXD 以及自定义四个选项，方便用户根据自己习惯可以自由切换。当用户选择自定义时，显示自定义 UI 名称和 UI 下载地址的输入框；选择预设选项时，则隐藏这些输入框。

**Comment by morytyann** [comment]
你无痕模式试试，去掉setup还能打开吗？

**Comment by Mikihta** [comment]
笑死估计是面板问题，在无痕浏览加`setup`都提示`Unauthorized`，看起来还是只有MetaCubeXD面板稳定点😂
之前openclash就遇到过，一直以为是bug😂

**Comment by morytyann** [comment]
嗯，他们三个连接不一样的，没法处理这个问题，默认兼容metacubexd的，想用其他的自己手动配置吧。

**Comment by Mikihta** [comment]
经查证测试，网址

```
http://[hostname]:[port]/ui/[面板名称]/?hostname=[hostname]&port=[port]&secret=[secret]
```
对于三个面板都能完美支持

**Comment by morytyann** [comment]
区别如下：
1. 参数不一致（host/hostname，这个其实可以通过把两个参数都加上来解决）
2. 路径不一致（这个就麻烦了，除非预先知道类型，否则处理不了）

**Comment by morytyann** [comment]
我试了一下，加上host参数以后，确实可以通用，Excellent！

**Comment by Mikihta** [comment]
感谢开发者的测试，我当时少删了一段字符，正准备晚上回去再测试一遍（刚刚我还在想明明通用来着🤣）

**Comment by morytyann** [comment]
OK，已更改，感谢❤️

**Comment by morytyann** [comment]
@Mikihta 你在群里吗？

**Comment by Mikihta** [comment]
Oxi（@Oximood）是也🤪
