### ISSUE TITLE
关于mihomo kernel形式的一些建议

### ISSUE THREAD

**Issue by liaoke01** [morytyann/OpenWrt-mihomo#87]
希望核心更新存在的形式可以和openclash一样,不将其作为软件包来安装,而是直接下载相对应的单个核心,这样做方便更新核心以及更改,不知可不可以改变？

**Comment by liaoke01** [comment]
写一个自动识别架构，下载相对应的内核到对应目录（套一个公益加速）,这样就不必要每次都重新打包内核了

**Comment by Mikihta** [comment]
咋说呢其实现在mihomo那个插件和open-mihomo算是耦合状态😂，mihomo那个插件里面有open-mihomo的相关配置（比如写入防火墙规则），现在的mihomo更像open-mihomo的一部分而不是单独的插件😂

**Comment by liaoke01** [comment]
> 咋说呢其实现在mihomo那个插件和open-mihomo算是耦合状态😂，mihomo那个插件里面有open-mihomo的相关配置（比如写入防火墙规则），现在的mihomo更像open-mihomo的一部分而不是单独的插件😂

希望能将这些配置合并到luci-app-mihomo,把内核单独隔离出来，也方便大家更换内核更新什么的

**Comment by morytyann** [comment]
Duplicate of #65

**Comment by morytyann** [comment]
不要再提这个Issue了……
还有提Issue之前先搜一下好不好😢

**Comment by liaoke01** [comment]
> 不要再提这个Issue了…… 还有提Issue之前先搜一下好不好😢

好的，抱歉
