### ISSUE TITLE
日志中出现大量的警告

### ISSUE THREAD

**Issue by liaoke01** [morytyann/OpenWrt-mihomo#89]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

快照版

### 插件版本

最新正式版

### 硬件架构

aarch64_generic

### BUG 描述

日志中出现大量的:
warning][TCP] dial DIRECT (match GeoIP/cn) 103.161.35.141:41832 --> 27.25.142.149:80 error: dial tcp 27.25.142.149:80: i/o timeout

warning][TCP] dial DIRECT (match GeoIP/cn) 103.161.35.140:33172 --> 110.40.37.212:7010 error: dial tcp 110.40.37.212:7010: connect: connection refused

类似这样的警告
然后导致dns无法查询

### 预期行为

修复这一bug

### 复现步骤

![Screenshot_2024-08-18-09-26-26-757_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/117e20a8-ecf1-440d-a925-eaf231db520a)
![Screenshot_2024-08-18-09-26-29-694_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/d884a3c7-6723-4aa2-ba28-18a216c125b0)
![Screenshot_2024-08-18-09-26-32-222_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/4a3abcba-87b4-4a8c-967f-22975aac98dc)
![Screenshot_2024-08-18-09-26-39-240_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/a3f858ea-ac52-48b3-863d-70fbdfc6984b)
![Screenshot_2024-08-18-09-26-41-490_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/224161ab-104f-41f8-95c4-e5ce699a2b07)
![Screenshot_2024-08-18-09-26-44-718_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/e5cfda7a-868b-49d4-ad2f-0a058c3ca61d)

**Comment by liaoke01** [comment]
根据我的观察，貌似tcp直连的流量都会导致无法连接

**Comment by liaoke01** [comment]
tcp走代理的流量可以正常连接

**Comment by morytyann** [comment]
`混入配置 -> 全局配置 -> 出栈接口`选一下wan接口试试。
话说你的敏感信息露出来了……你抓紧删了这个Issue再重新创建吧！

**Comment by liaoke01** [comment]
> `混入配置 -> 全局配置 -> 出栈接口`选一下wan接口试试。 话说你的敏感信息露出来了……你抓紧删了这个Issue再重新创建吧！

已删除敏感信息，我设置了之后照样会频繁出现警告。

**Comment by morytyann** [comment]
不行，你得删掉，这里有编辑记录的……

**Comment by morytyann** [comment]
我来删吧，可以吗？
