### ISSUE TITLE
建议增加 *使用Dnsmasq 转发*和*禁止 Dnsmasq 缓存 DNS*选项。

### ISSUE THREAD

**Issue by y9858** [morytyann/OpenWrt-mihomo#9]
虽然这2个选项都可以手动配置，但是略嫌麻烦。

**Comment by 350048663** [comment]
个人觉得维持现在用nftables转发比较简单

**Comment by morytyann** [comment]
设计之初没有添加这两个选项的原因：
1. 这两个选项生效需要侵入式的修改dnsmasq的配置，个人认为这是不被允许的行为
2. 使用dnsmasq转发时，fake-ip模式下无法进行访问控制，因为dnsmasq不能根据客户端分流

不过应该可以添加一个劫持DNS的开关，便于与其他DNS插件配合使用

**Comment by y9858** [comment]
> 设计之初没有指定该选项的原因：
> 
> 1. 这两个选项生效需要侵入式的修改dnsmasq的配置，个人认为这是不被允许的行为
> 2. 使用dnsmasq转发时，fake-ip模式下无法进行访问控制，因为dnsmasq不能根据客户端分流
> 
> 不过应该可以添加一个劫持DNS的开关，以便于其他DNS插件协同使用，

支持，有用到adg和mosdns。

**Comment by morytyann** [comment]
已添加DNS劫持的开关，关闭后将不再劫持DNS请求到核心
