### ISSUE TITLE
日志中出现大量的警告

### ISSUE THREAD

**Issue by liaoke01** [morytyann/OpenWrt-mihomo#90]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

快照版。

### 插件版本

最新正式版。

### 硬件架构

aarch64_generic

### BUG 描述

日志中出现大量关于tcp直连的报错。

### 预期行为

修复该报错。

### 复现步骤

![屏幕截图 2024-08-18 102041](https://github.com/user-attachments/assets/02e49ab3-c1ad-4e73-99ff-d06ae6938c9d)
![屏幕截图 2024-08-18 102047](https://github.com/user-attachments/assets/ea6c8a2e-df4a-4ae4-b490-a63083e49486)
![屏幕截图 2024-08-18 102106](https://github.com/user-attachments/assets/1df1740f-f03c-4812-8003-5b78f62eb012)
![屏幕截图 2024-08-18 102116](https://github.com/user-attachments/assets/8bf3a36a-bdf8-473a-b494-c3a68684f5d9)
![屏幕截图 2024-08-18 102128](https://github.com/user-attachments/assets/a6a61d16-7a73-4fe6-8fef-242e2da59495)
![屏幕截图 2024-08-18 102139](https://github.com/user-attachments/assets/eb00fd94-42f0-4ac8-91bd-aef738746bc4)

**Comment by morytyann** [comment]
我之前遇到过相同的问题，是通过设置出站接口解决的，能否请你重启下插件再测试是否正常？

**Comment by liaoke01** [comment]
> 我之前遇到过相同的问题，是通过设置出站接口解决的，能否请你重启下插件再测试是否正常？

ok,已经正常了。是否可以添加tcp tproxy +udp tun混合模式。这样性能更高。

**Comment by morytyann** [comment]
嗯，多测试一下，没问题了再来关掉Issue吧。

混合模式再说吧，可以先着用TPROXY模式
