### ISSUE TITLE
[BUG]订阅无法正确传递ua

### ISSUE THREAD

**Issue by codetiger666** [morytyann/OpenWrt-mihomo#91]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

OpenWrt

### 系统版本

23.04

### 插件版本

1.6.4

### 硬件架构

aarch64_cortex-a53

### BUG 描述

使用订阅地址时，无法正确传递ua,请求头中不存在user-agent

### 预期行为

请求头中传递正确的user-agent

### 复现步骤

请求订阅地址

**Comment by morytyann** [comment]
试试v1.6.5

**Comment by codetiger666** [comment]
晚上回去试试

**Comment by hsiangyeung** [comment]
> 试试v1.6.5

好像使用订阅转换默认不开启udp，转换时没有启用udp选项

**Comment by codetiger666** [comment]
> 试试v1.6.5

可以用了

**Comment by codetiger666** [comment]
可以正常使用
