### ISSUE TITLE
[BUG]nslookup www.google.com  应答为www.google.com.lan

### ISSUE THREAD

**Issue by liumingan** [morytyann/OpenWrt-mihomo#92]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

OpenWrt

### 系统版本

OpenWrt SNAPSHOT r27160-b72c4b5386 / LuCI Master 24.212.79282~65b8002

### 插件版本

1.6.5

### 硬件架构

arm_cortex-a9

### BUG 描述

设置DNS模式为fake-ip，覆盖+.*,不管是否关闭混写，nslookup www.google.com,都会返回www.google.com.lan.
配置文件设置为redir-host

### 预期行为

x修复

### 复现步骤

设置DNS模式为fake-ip，覆盖+.*,不管是否关闭混写，nslookup www.google.com,都会返回www.google.com.lan.

**Comment by morytyann** [comment]
是不是用Windows运行的nslookup？

**Comment by morytyann** [comment]
还有既然不想返回Fake-IP，为什么不直接用Redir-Host模式……

**Comment by morytyann** [comment]
进入nslookup的交互式命令行，设置debug模式，查询任意域名，你会发现它先查询了添加了.lan的域名，Fake-IP模式下，查询任何域名，哪怕不存在的，都能返回结果，这两者结合起来就出现了你说的"问题"。
![image](https://github.com/user-attachments/assets/d9ae298a-05e6-454a-974b-7e95dd8d2715)
你可以用PowerShell运行`Resolve-DnsName www.google.com`，它是不会画蛇添足的查询添加.lan的域名，你会发现结果是正常的。

**Comment by morytyann** [comment]
为什么追加的是.lan，和你的`网络 -> DHCP/DNS -> 常规 -> 本地域名`有关，如果想要让nslookup"正常"查询，你可以删掉这一项，保存并应用，再在电脑重新获取DHCP（`ipconfig /renew`）。

**Comment by morytyann** [comment]
或者在nslookup时在域名最后面追加一个`.`（英文句点），这样不会追加.lan。例如`nslookup www.google.com.`。
![image](https://github.com/user-attachments/assets/0ea5b7cc-e74c-4a16-a1ef-4f0e55e2c96b)

**Comment by liumingan** [comment]
DNS不是已经挟持到1053端口了 吗？为什么dnsmasq还会应答呢？

**Comment by liumingan** [comment]
并且上个版本就没有这个问题，所有还是不明白？

**Comment by morytyann** [comment]
呃，没说是DNSMASQ应答的啊，只是说他的设置会影响你说的这个"问题"，你有没有按我说的方法测试看结果是否"正常"呢？

**Comment by morytyann** [comment]
给你个微软官方的[参考链接](https://learn.microsoft.com/en-us/archive/msdn-technet-forums/913b56b8-f7e5-4988-8fdd-5c8e479d64d9)，关于这个追加.lan行为的。

**Comment by morytyann** [comment]
话说你说的上个版本是哪一个？我看了下只有v1.6.1有相关改动，请问是v1.6.1吗？两个版本你的配置是一致的吗？

**Comment by morytyann** [comment]
没有后续回复的话我就先关咯❤️
