### ISSUE TITLE
[Feature Request]是否可以在混入文件中追加规则，不进行覆盖重写，变成追加模式

### ISSUE THREAD

**Issue by kuke2733** [morytyann/OpenWrt-mihomo#97]
我想单独添加一条规则，我在混入文件中添加了一条规则
![image](https://github.com/user-attachments/assets/a1953a52-4aa8-4e58-aa92-7a264c4f2975)
然后点击保存应用的时候，会重写覆盖订阅的规则，然后就变成了只有我这一条订阅规则
作者是否可以修改一下混入文件的重写模式，增加规则追加的模式

**Comment by morytyann** [comment]
这个只能约定一个模式，我觉得覆盖是最好的，至少能用。

追加模式，也要分情况：
1. 如果规定追加到末尾，对于rules来说没有意义，因为最后一条是Match，没有匹配到的都会走这个，追加到他后面没有意义，除非你特意的在配置文件里不写Match……不过既然你已经编辑配置文件了，为何还要混入呢，直接一次性配置好更好。
2. 如果说是批量插入到指定位置，这个其实并不灵活。
3. 如果说是单条插入到指定位置，这个太复杂了，没必要，不如直接覆盖掉方便。你还要验证是否生效，还牵扯前面插入的规则影响后面的插入位置。

这也是混入配置没有单独做rules的原因。

**Comment by morytyann** [comment]
如果一定要做的话，我将在混入配置添加rules的标签，会做成单条插入到指定位置的模式（需要按插入位置从大到小来配置）。
大家（在这条回复上）投投票吧，赞同的点👍，不赞同点👎。

**Comment by morytyann** [comment]
> 建议自己写一份配置文件

确实，但是为了照顾小白，没有办法。有个界面可以点点点就配置好文件了，至少看起来非常友好。

> 订阅和订阅转换就挺多余

订阅还是有用的，订阅转换确实没必要，毕竟可以直接填转换后的链接，只能说当时头昏了，看以后能不能移除掉订阅转换吧。

> 使用JS来自定义覆写

是指类似于`Clash For Windows`那种吗？在路由器实现的话需要Node环境来执行JS脚本，还要再依赖一个Node，只是为了这一个功能的话我觉得不行。

**Comment by liumingan** [comment]
建议去掉订阅转换，不要追加，也去掉追加，改配置在编辑器里完成就可以了，现在有个问题是改配置后不能保存，因为重启后就又同步远程文件了，建议把同步远程订阅单独出来编辑器里改本地文件

**Comment by liumingan** [comment]
我是把混写关闭的，全部在配置文件中写好

**Comment by morytyann** [comment]
> 改配置后不能保存

不支持修改来自订阅的配置文件，如果你想修改运行中的配置文件用于测试，你可以点保存按钮而不是保存并应用，这将不会触发service的reload，然后去面板重新加载。

**Comment by morytyann** [comment]
`QuickJS`还需要构建，算了算了。

有点跑题了，关于追加规则这个就不改了，还是保持现在的行为（覆盖）， @kuke2733 如果你想修改rules，你可以选择在混入文件里覆盖，或者直接手动编写配置文件上传，可以参考官方文档的示例。

感谢你的Issue。❤️

**Comment by kuke2733** [comment]
> `QuickJS`还需要构建，算了算了。
> 
> 有点跑题了，关于追加规则这个就不改了，还是保持现在的行为（覆盖）， @kuke2733 如果你想修改rules，你可以选择在混入文件里覆盖，或者直接手动编写配置文件上传，可以参考官方文档的示例。
> 
> 感谢你的Issue。❤️

行叭，之前在提issue之前，是因为一个程序的联网都这个代理会直接进行联通，后来发现改本地hosts也可以实现，覆写规则就没有多大的必要了

**Comment by gbsadmin** [comment]
将订阅后的 规则 提取后，单独列在一个标签或选择列表，启动时直接整体替换覆盖

**Comment by xixi-furry** [comment]
主要喜欢追加模式这个，在机场里的规则通过订阅转换成其他的规则后，再想添加就很麻烦了，虽然可以直接修改原有的部分，但是订阅一般是喜欢更新的，一旦更新就得重新写。而且似乎也没有订阅自动更新功能（？

**Comment by refined-fish** [comment]
> 主要喜欢追加模式这个，在机场里的规则通过订阅转换成其他的规则后，再想添加就很麻烦了，虽然可以直接修改原有的部分，但是订阅一般是喜欢更新的，一旦更新就得重新写。而且似乎也没有订阅自动更新功能（？

你可以通过维护自己的定远转换模板来生成你喜欢的配置文件，这个是最完美的解法。另外自动更新通过选择远程优先并重启实现
